namespace Test.Shared.Infrastructure
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Globalization;
    using System.IO;
    using System.Text;

    /// <summary>
    /// Turns off automatic git maintenance and automatic garbage collection for every git process a test host
    /// starts. Git runs <c>git maintenance run --auto</c> after commands such as commit, merge, fetch and a
    /// received push; in the short-lived repositories tests create that work is pure process start-up cost.
    /// Production defaults are unchanged: the settings live only in the test host's environment, so test helpers
    /// and the production code under test inherit them. Every test entry point calls
    /// <see cref="DisableAutoMaintenance"/> before any test runs.
    /// <para>
    /// Two layers are needed. <c>GIT_CONFIG_COUNT</c> / <c>GIT_CONFIG_KEY_n</c> / <c>GIT_CONFIG_VALUE_n</c> give
    /// the settings command-line precedence for the git processes the host starts. Git's local transport clears
    /// those variables before it starts <c>git-receive-pack</c> or <c>git-upload-pack</c> in the other repository,
    /// so a push to a file-path remote would still run maintenance there. <c>GIT_CONFIG_SYSTEM</c> is not cleared,
    /// so the host also points it at a generated system configuration that includes the original system file and
    /// adds the same settings.
    /// </para>
    /// </summary>
    public static class TestGitEnvironment
    {
        #region Public-Members

        /// <summary>
        /// Environment variable that holds the number of injected git configuration entries.
        /// </summary>
        public const string CountVariable = "GIT_CONFIG_COUNT";

        /// <summary>
        /// Environment variable that names the git system configuration file.
        /// </summary>
        public const string SystemVariable = "GIT_CONFIG_SYSTEM";

        /// <summary>
        /// First line of a generated system configuration, used to avoid wrapping a generated file twice.
        /// </summary>
        public const string GeneratedMarker = "# Generated by the Armada test host: git auto maintenance off.";

        /// <summary>
        /// Git configuration entries applied to test processes, by key.
        /// </summary>
        public static readonly IReadOnlyDictionary<string, string> Settings = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "maintenance.auto", "false" },
            { "gc.auto", "0" },
            { "receive.autogc", "false" }
        };

        #endregion

        #region Public-Methods

        /// <summary>
        /// Compute the environment variables that add <see cref="Settings"/> to the git configuration entries
        /// already present. Existing entries are kept; a setting whose key and value are already injected is not
        /// added twice.
        /// </summary>
        /// <param name="lookup">Reads the current value of an environment variable, or null when unset.</param>
        /// <returns>Variable names and the values to set. Empty when nothing needs to change.</returns>
        /// <exception cref="InvalidOperationException">The existing count is not a non-negative integer.</exception>
        public static Dictionary<string, string> ComputeVariables(Func<string, string?> lookup)
        {
            ArgumentNullException.ThrowIfNull(lookup);

            int count = 0;
            string? rawCount = lookup(CountVariable);
            if (!String.IsNullOrEmpty(rawCount)
                && (!Int32.TryParse(rawCount, NumberStyles.None, CultureInfo.InvariantCulture, out count) || count < 0))
            {
                throw new InvalidOperationException(CountVariable + " is set to '" + rawCount
                    + "', which is not a non-negative integer; git would reject every command.");
            }

            HashSet<string> present = new HashSet<string>(StringComparer.Ordinal);
            for (int i = 0; i < count; i++)
            {
                string? key = lookup("GIT_CONFIG_KEY_" + i.ToString(CultureInfo.InvariantCulture));
                string? value = lookup("GIT_CONFIG_VALUE_" + i.ToString(CultureInfo.InvariantCulture));
                if (key != null && value != null) present.Add(key + "=" + value);
            }

            Dictionary<string, string> result = new Dictionary<string, string>(StringComparer.Ordinal);
            int next = count;
            foreach (KeyValuePair<string, string> setting in Settings)
            {
                if (present.Contains(setting.Key + "=" + setting.Value)) continue;
                string index = next.ToString(CultureInfo.InvariantCulture);
                result["GIT_CONFIG_KEY_" + index] = setting.Key;
                result["GIT_CONFIG_VALUE_" + index] = setting.Value;
                next++;
            }

            if (next != count) result[CountVariable] = next.ToString(CultureInfo.InvariantCulture);
            return result;
        }

        /// <summary>
        /// Build the text of a generated system configuration: an include of the original system file, so its
        /// settings still apply, followed by <see cref="Settings"/>.
        /// </summary>
        /// <param name="originalSystemPath">Absolute path of the system file to include, or null for none.</param>
        /// <returns>Git configuration file text.</returns>
        public static string BuildSystemConfig(string? originalSystemPath)
        {
            StringBuilder builder = new StringBuilder();
            builder.Append(GeneratedMarker).Append('\n');
            if (!String.IsNullOrWhiteSpace(originalSystemPath))
            {
                // Git ignores an include whose file does not exist, so a host without a system file is fine.
                builder.Append("[include]\n\tpath = \"")
                    .Append(originalSystemPath.Replace("\\", "\\\\").Replace("\"", "\\\""))
                    .Append("\"\n");
            }

            foreach (KeyValuePair<string, string> setting in Settings)
            {
                int dot = setting.Key.LastIndexOf('.');
                builder.Append('[').Append(setting.Key.Substring(0, dot)).Append("]\n\t")
                    .Append(setting.Key.Substring(dot + 1)).Append(" = ").Append(setting.Value).Append('\n');
            }

            return builder.ToString();
        }

        /// <summary>
        /// Apply <see cref="Settings"/> to this process's environment so every git child process inherits them,
        /// including the processes git's local transport starts in another repository. Prints one line when the
        /// system configuration layer cannot be applied, naming what stays on.
        /// </summary>
        public static void DisableAutoMaintenance()
        {
            Dictionary<string, string> variables = ComputeVariables(Environment.GetEnvironmentVariable);
            foreach (KeyValuePair<string, string> variable in variables)
            {
                Environment.SetEnvironmentVariable(variable.Key, variable.Value);
            }

            string? currentSystem = Environment.GetEnvironmentVariable(SystemVariable);
            if (!String.IsNullOrEmpty(currentSystem) && IsGenerated(currentSystem)) return;

            string reason = "";
            string? originalSystem = !String.IsNullOrEmpty(currentSystem) ? currentSystem : ReadDefaultSystemPath(out reason);
            if (originalSystem == null)
            {
                Console.WriteLine("Git system configuration not replaced (" + reason
                    + "); a push to a file-path remote still runs auto maintenance in that repository.");
                return;
            }

            string generated = Path.Combine(Path.GetTempPath(),
                "armada-test-git-" + Environment.ProcessId.ToString(CultureInfo.InvariantCulture) + ".gitconfig");
            File.WriteAllText(generated, BuildSystemConfig(originalSystem));
            Environment.SetEnvironmentVariable(SystemVariable, generated);
            AppDomain.CurrentDomain.ProcessExit += (sender, args) =>
            {
                try
                {
                    File.Delete(generated);
                }
                catch (IOException)
                {
                    // A leftover file in the temp directory is harmless; the next host writes its own.
                }
                catch (UnauthorizedAccessException)
                {
                    // Same as above.
                }
            };
        }

        #endregion

        #region Private-Methods

        private static bool IsGenerated(string path)
        {
            try
            {
                if (!File.Exists(path)) return false;
                using (StreamReader reader = new StreamReader(path))
                {
                    return String.Equals(reader.ReadLine(), GeneratedMarker, StringComparison.Ordinal);
                }
            }
            catch (IOException)
            {
                return false;
            }
        }

        private static string? ReadDefaultSystemPath(out string reason)
        {
            ProcessStartInfo start = new ProcessStartInfo("git")
            {
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false
            };
            start.ArgumentList.Add("var");
            start.ArgumentList.Add(SystemVariable);
            try
            {
                using (Process process = Process.Start(start) ?? throw new InvalidOperationException("git did not start"))
                {
                    string output = process.StandardOutput.ReadToEnd();
                    string error = process.StandardError.ReadToEnd();
                    process.WaitForExit();
                    string path = output.Trim();
                    if (process.ExitCode != 0 || path.Length == 0)
                    {
                        reason = "'git var " + SystemVariable + "' failed: " + error.Trim();
                        return null;
                    }

                    reason = "";
                    return path;
                }
            }
            catch (Exception ex) when (ex is InvalidOperationException || ex is System.ComponentModel.Win32Exception)
            {
                reason = "git could not be started: " + ex.Message;
                return null;
            }
        }

        #endregion
    }
}
