<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Core models, database, and services for Armada multi-agent orchestration</Description>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Test.Shared" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="MySqlConnector" Version="2.6.1" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="PrettyId" Version="2.0.1" />
    <PackageReference Include="SyslogLogging" Version="2.1.0" />
  </ItemGroup>

</Project>
