namespace Armada.Core.Database.SqlServer.Queries
{
    /// <summary>
    /// Additive prerequisites omitted from the historical server migration sequence.
    /// Applied migration declarations and ledger rows remain unchanged.
    /// </summary>
    internal static class ForkOperationalSchema
    {
        internal static readonly string[] Statements = new string[]
        {
            @"ALTER TABLE vessels ADD github_token_override NVARCHAR(MAX);",
            @"CREATE TABLE request_history (
                        id NVARCHAR(450) NOT NULL PRIMARY KEY,
                        tenant_id NVARCHAR(450),
                        user_id NVARCHAR(450),
                        credential_id NVARCHAR(450),
                        principal_display NVARCHAR(MAX),
                        auth_method NVARCHAR(MAX),
                        method NVARCHAR(MAX) NOT NULL,
                        route NVARCHAR(450) NOT NULL,
                        route_template NVARCHAR(MAX),
                        query_string NVARCHAR(MAX),
                        status_code INT NOT NULL,
                        duration_ms FLOAT NOT NULL DEFAULT 0,
                        request_size_bytes BIGINT NOT NULL DEFAULT 0,
                        response_size_bytes BIGINT NOT NULL DEFAULT 0,
                        request_content_type NVARCHAR(MAX),
                        response_content_type NVARCHAR(MAX),
                        is_success BIT NOT NULL DEFAULT 0,
                        client_ip NVARCHAR(MAX),
                        correlation_id NVARCHAR(450),
                        created_utc NVARCHAR(450) NOT NULL
                    );",
            @"CREATE TABLE request_history_detail (
                        request_history_id NVARCHAR(450) NOT NULL PRIMARY KEY,
                        path_params_json NVARCHAR(MAX),
                        query_params_json NVARCHAR(MAX),
                        request_headers_json NVARCHAR(MAX),
                        response_headers_json NVARCHAR(MAX),
                        request_body_text NVARCHAR(MAX),
                        response_body_text NVARCHAR(MAX),
                        request_body_truncated BIT NOT NULL DEFAULT 0,
                        response_body_truncated BIT NOT NULL DEFAULT 0,
                        FOREIGN KEY (request_history_id) REFERENCES request_history(id) ON DELETE CASCADE
                    );",
            @"CREATE TABLE workflow_profiles (
                        id NVARCHAR(450) NOT NULL PRIMARY KEY,
                        tenant_id NVARCHAR(450),
                        user_id NVARCHAR(450),
                        name NVARCHAR(MAX) NOT NULL,
                        description NVARCHAR(MAX),
                        scope NVARCHAR(450) NOT NULL DEFAULT 'Global',
                        fleet_id NVARCHAR(450),
                        vessel_id NVARCHAR(450),
                        is_default BIT NOT NULL DEFAULT 0,
                        active BIT NOT NULL DEFAULT 1,
                        language_hints_json NVARCHAR(MAX) NOT NULL DEFAULT '[]',
                        environment_variables_json NVARCHAR(MAX),
                        lint_command NVARCHAR(MAX),
                        build_command NVARCHAR(MAX),
                        unit_test_command NVARCHAR(MAX),
                        containerless_unit_test_command NVARCHAR(MAX),
                        integration_test_command NVARCHAR(MAX),
                        e2e_test_command NVARCHAR(MAX),
                        package_command NVARCHAR(MAX),
                        publish_artifact_command NVARCHAR(MAX),
                        release_versioning_command NVARCHAR(MAX),
                        changelog_generation_command NVARCHAR(MAX),
                        migration_command NVARCHAR(MAX),
                        security_scan_command NVARCHAR(MAX),
                        performance_command NVARCHAR(MAX),
                        deployment_verification_command NVARCHAR(MAX),
                        rollback_verification_command NVARCHAR(MAX),
                        required_secrets_json NVARCHAR(MAX) NOT NULL DEFAULT '[]',
                        expected_artifacts_json NVARCHAR(MAX) NOT NULL DEFAULT '[]',
                        environments_json NVARCHAR(MAX) NOT NULL DEFAULT '[]',
                        created_utc NVARCHAR(450) NOT NULL,
                        last_update_utc NVARCHAR(450) NOT NULL
                    );",
            @"CREATE TABLE check_runs (
                        id NVARCHAR(450) NOT NULL PRIMARY KEY,
                        tenant_id NVARCHAR(450),
                        user_id NVARCHAR(450),
                        workflow_profile_id NVARCHAR(450),
                        vessel_id NVARCHAR(450),
                        mission_id NVARCHAR(450),
                        voyage_id NVARCHAR(450),
                        deployment_id NVARCHAR(450),
                        label NVARCHAR(MAX),
                        check_type NVARCHAR(MAX) NOT NULL,
                        status NVARCHAR(450) NOT NULL,
                        source NVARCHAR(MAX) NOT NULL,
                        provider_name NVARCHAR(MAX),
                        external_id NVARCHAR(450),
                        external_url NVARCHAR(MAX),
                        environment_name NVARCHAR(MAX),
                        command NVARCHAR(MAX) NOT NULL,
                        working_directory NVARCHAR(MAX),
                        branch_name NVARCHAR(MAX),
                        commit_hash NVARCHAR(MAX),
                        exit_code INT,
                        output NVARCHAR(MAX),
                        summary NVARCHAR(MAX),
                        test_summary_json NVARCHAR(MAX),
                        coverage_summary_json NVARCHAR(MAX),
                        artifacts_json NVARCHAR(MAX) NOT NULL DEFAULT '[]',
                        duration_ms BIGINT,
                        started_utc NVARCHAR(450),
                        completed_utc NVARCHAR(450),
                        created_utc NVARCHAR(450) NOT NULL,
                        last_update_utc NVARCHAR(450) NOT NULL
                    );",
            @"CREATE TABLE environments (
                        id NVARCHAR(450) NOT NULL PRIMARY KEY,
                        tenant_id NVARCHAR(450),
                        user_id NVARCHAR(450),
                        vessel_id NVARCHAR(450),
                        name NVARCHAR(MAX) NOT NULL,
                        description NVARCHAR(MAX),
                        kind NVARCHAR(450) NOT NULL,
                        configuration_source NVARCHAR(MAX),
                        base_url NVARCHAR(MAX),
                        health_endpoint NVARCHAR(MAX),
                        access_notes NVARCHAR(MAX),
                        deployment_rules NVARCHAR(MAX),
                        verification_definitions_json NVARCHAR(MAX) NOT NULL DEFAULT '[]',
                        rollout_monitoring_window_minutes INT NOT NULL DEFAULT 0,
                        rollout_monitoring_interval_seconds INT NOT NULL DEFAULT 300,
                        alert_on_regression BIT NOT NULL DEFAULT 1,
                        requires_approval BIT NOT NULL DEFAULT 0,
                        is_default BIT NOT NULL DEFAULT 0,
                        active BIT NOT NULL DEFAULT 1,
                        created_utc NVARCHAR(450) NOT NULL,
                        last_update_utc NVARCHAR(450) NOT NULL
                    );",
            @"CREATE TABLE releases (
                        id NVARCHAR(450) NOT NULL PRIMARY KEY,
                        tenant_id NVARCHAR(450),
                        user_id NVARCHAR(450),
                        vessel_id NVARCHAR(450),
                        workflow_profile_id NVARCHAR(450),
                        title NVARCHAR(MAX) NOT NULL,
                        version NVARCHAR(MAX),
                        tag_name NVARCHAR(MAX),
                        summary NVARCHAR(MAX),
                        notes NVARCHAR(MAX),
                        status NVARCHAR(450) NOT NULL,
                        voyage_ids_json NVARCHAR(MAX) NOT NULL DEFAULT '[]',
                        mission_ids_json NVARCHAR(MAX) NOT NULL DEFAULT '[]',
                        check_run_ids_json NVARCHAR(MAX) NOT NULL DEFAULT '[]',
                        artifacts_json NVARCHAR(MAX) NOT NULL DEFAULT '[]',
                        created_utc NVARCHAR(450) NOT NULL,
                        last_update_utc NVARCHAR(450) NOT NULL,
                        published_utc NVARCHAR(450)
                    );",
            @"CREATE TABLE deployments (
                        id NVARCHAR(450) NOT NULL PRIMARY KEY,
                        tenant_id NVARCHAR(450),
                        user_id NVARCHAR(450),
                        vessel_id NVARCHAR(450),
                        workflow_profile_id NVARCHAR(450),
                        environment_id NVARCHAR(450),
                        environment_name NVARCHAR(MAX),
                        release_id NVARCHAR(450),
                        mission_id NVARCHAR(450),
                        voyage_id NVARCHAR(450),
                        title NVARCHAR(MAX) NOT NULL,
                        source_ref NVARCHAR(MAX),
                        summary NVARCHAR(MAX),
                        notes NVARCHAR(MAX),
                        status NVARCHAR(450) NOT NULL,
                        verification_status NVARCHAR(MAX) NOT NULL,
                        approval_required BIT NOT NULL DEFAULT 0,
                        approved_by_user_id NVARCHAR(450),
                        approved_utc NVARCHAR(450),
                        approval_comment NVARCHAR(MAX),
                        deploy_check_run_id NVARCHAR(450),
                        smoke_test_check_run_id NVARCHAR(450),
                        health_check_run_id NVARCHAR(450),
                        deployment_verification_check_run_id NVARCHAR(450),
                        rollback_check_run_id NVARCHAR(450),
                        rollback_verification_check_run_id NVARCHAR(450),
                        check_run_ids_json NVARCHAR(MAX) NOT NULL DEFAULT '[]',
                        request_history_summary_json NVARCHAR(MAX),
                        created_utc NVARCHAR(450) NOT NULL,
                        started_utc NVARCHAR(450),
                        completed_utc NVARCHAR(450),
                        verified_utc NVARCHAR(450),
                        rolled_back_utc NVARCHAR(450),
                        monitoring_window_ends_utc NVARCHAR(450),
                        last_monitored_utc NVARCHAR(450),
                        last_regression_alert_utc NVARCHAR(450),
                        latest_monitoring_summary NVARCHAR(MAX),
                        monitoring_failure_count INT NOT NULL DEFAULT 0,
                        last_update_utc NVARCHAR(450) NOT NULL
                    );",
            @"CREATE INDEX idx_request_history_tenant_created ON request_history(tenant_id, created_utc DESC);",
            @"CREATE INDEX idx_request_history_user_created ON request_history(user_id, created_utc DESC);",
            @"CREATE INDEX idx_request_history_route_created ON request_history(route, created_utc DESC);",
            @"CREATE INDEX idx_workflow_profiles_tenant_scope ON workflow_profiles(tenant_id, scope);",
            @"CREATE INDEX idx_workflow_profiles_fleet ON workflow_profiles(fleet_id);",
            @"CREATE INDEX idx_workflow_profiles_vessel ON workflow_profiles(vessel_id);",
            @"CREATE INDEX idx_check_runs_tenant_created ON check_runs(tenant_id, created_utc DESC);",
            @"CREATE INDEX idx_check_runs_vessel_created ON check_runs(vessel_id, created_utc DESC);",
            @"CREATE INDEX idx_check_runs_mission_created ON check_runs(mission_id, created_utc DESC);",
            @"CREATE INDEX idx_check_runs_deployment_created ON check_runs(deployment_id, created_utc DESC);",
            @"CREATE INDEX idx_environments_tenant_vessel ON environments(tenant_id, vessel_id);",
            @"CREATE INDEX idx_environments_vessel_kind ON environments(vessel_id, kind);",
            @"CREATE INDEX idx_releases_tenant_created ON releases(tenant_id, created_utc DESC);",
            @"CREATE INDEX idx_releases_vessel_created ON releases(vessel_id, created_utc DESC);",
            @"CREATE INDEX idx_releases_status_created ON releases(status, created_utc DESC);",
            @"CREATE INDEX idx_deployments_tenant_created ON deployments(tenant_id, created_utc DESC);",
            @"CREATE INDEX idx_deployments_vessel_created ON deployments(vessel_id, created_utc DESC);",
            @"CREATE INDEX idx_deployments_status_created ON deployments(status, created_utc DESC);",
            @"CREATE INDEX idx_deployments_environment_created ON deployments(environment_id, created_utc DESC);",
            @"CREATE TABLE objectives (
    id NVARCHAR(450) NOT NULL PRIMARY KEY,
    tenant_id NVARCHAR(450),
    user_id NVARCHAR(450),
    title NVARCHAR(450) NOT NULL,
    description NVARCHAR(MAX),
    status NVARCHAR(64) NOT NULL DEFAULT 'Draft',
    kind NVARCHAR(64) NOT NULL DEFAULT 'Feature',
    category NVARCHAR(450),
    priority NVARCHAR(64) NOT NULL DEFAULT 'P2',
    rank INT NOT NULL DEFAULT 0,
    backlog_state NVARCHAR(64) NOT NULL DEFAULT 'Inbox',
    effort NVARCHAR(64) NOT NULL DEFAULT 'M',
    owner NVARCHAR(450),
    target_version NVARCHAR(450),
    due_utc NVARCHAR(450),
    parent_objective_id NVARCHAR(450),
    blocked_by_objective_ids_json NVARCHAR(MAX),
    refinement_summary NVARCHAR(MAX),
    suggested_pipeline_id NVARCHAR(450),
    suggested_playbooks_json NVARCHAR(MAX),
    tags_json NVARCHAR(MAX),
    acceptance_criteria_json NVARCHAR(MAX),
    non_goals_json NVARCHAR(MAX),
    rollout_constraints_json NVARCHAR(MAX),
    evidence_links_json NVARCHAR(MAX),
    fleet_ids_json NVARCHAR(MAX),
    vessel_ids_json NVARCHAR(MAX),
    planning_session_ids_json NVARCHAR(MAX),
    refinement_session_ids_json NVARCHAR(MAX),
    voyage_ids_json NVARCHAR(MAX),
    mission_ids_json NVARCHAR(MAX),
    check_run_ids_json NVARCHAR(MAX),
    release_ids_json NVARCHAR(MAX),
    deployment_ids_json NVARCHAR(MAX),
    incident_ids_json NVARCHAR(MAX),
    source_provider NVARCHAR(450),
    source_type NVARCHAR(450),
    source_id NVARCHAR(450),
    source_url NVARCHAR(MAX),
    source_updated_utc NVARCHAR(450),
    created_utc NVARCHAR(450) NOT NULL,
    last_update_utc NVARCHAR(450) NOT NULL,
    completed_utc NVARCHAR(450),
    CONSTRAINT FK_objectives_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT FK_objectives_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT FK_objectives_parent FOREIGN KEY (parent_objective_id) REFERENCES objectives(id),
    CONSTRAINT FK_objectives_pipeline FOREIGN KEY (suggested_pipeline_id) REFERENCES pipelines(id)
);",
            @"CREATE INDEX idx_objectives_tenant_status_updated ON objectives(tenant_id, status, last_update_utc DESC);",
            @"CREATE INDEX idx_objectives_tenant_backlog_priority_rank ON objectives(tenant_id, backlog_state, priority, rank);",
            @"CREATE INDEX idx_objectives_tenant_kind_priority ON objectives(tenant_id, kind, priority);",
            @"CREATE INDEX idx_objectives_tenant_owner ON objectives(tenant_id, owner);",
            @"CREATE INDEX idx_objectives_tenant_due ON objectives(tenant_id, due_utc);",
            @"CREATE INDEX idx_objectives_tenant_target_version ON objectives(tenant_id, target_version);",
            @"CREATE INDEX idx_objectives_tenant_parent ON objectives(tenant_id, parent_objective_id);",
            @"CREATE INDEX idx_objectives_tenant_source ON objectives(tenant_id, source_provider, source_type, source_id);",
            @"CREATE TABLE objective_refinement_sessions (
    id NVARCHAR(450) NOT NULL PRIMARY KEY,
    objective_id NVARCHAR(450) NOT NULL,
    tenant_id NVARCHAR(450),
    user_id NVARCHAR(450),
    captain_id NVARCHAR(450) NOT NULL,
    fleet_id NVARCHAR(450),
    vessel_id NVARCHAR(450),
    title NVARCHAR(450) NOT NULL,
    status NVARCHAR(64) NOT NULL DEFAULT 'Created',
    process_id INT NULL,
    failure_reason NVARCHAR(MAX),
    created_utc NVARCHAR(450) NOT NULL,
    started_utc NVARCHAR(450),
    completed_utc NVARCHAR(450),
    last_update_utc NVARCHAR(450) NOT NULL,
    CONSTRAINT FK_objective_refinement_sessions_objective FOREIGN KEY (objective_id) REFERENCES objectives(id) ON DELETE CASCADE,
    CONSTRAINT FK_objective_refinement_sessions_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT FK_objective_refinement_sessions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT FK_objective_refinement_sessions_captain FOREIGN KEY (captain_id) REFERENCES captains(id),
    CONSTRAINT FK_objective_refinement_sessions_fleet FOREIGN KEY (fleet_id) REFERENCES fleets(id),
    CONSTRAINT FK_objective_refinement_sessions_vessel FOREIGN KEY (vessel_id) REFERENCES vessels(id)
);",
            @"CREATE INDEX idx_objective_refinement_sessions_tenant_objective_created ON objective_refinement_sessions(tenant_id, objective_id, created_utc DESC);",
            @"CREATE INDEX idx_objective_refinement_sessions_tenant_captain_status ON objective_refinement_sessions(tenant_id, captain_id, status);",
            @"CREATE TABLE objective_refinement_messages (
    id NVARCHAR(450) NOT NULL PRIMARY KEY,
    objective_refinement_session_id NVARCHAR(450) NOT NULL,
    objective_id NVARCHAR(450) NOT NULL,
    tenant_id NVARCHAR(450),
    user_id NVARCHAR(450),
    role NVARCHAR(64) NOT NULL,
    sequence INT NOT NULL,
    content NVARCHAR(MAX) NOT NULL,
    is_selected BIT NOT NULL DEFAULT 0,
    created_utc NVARCHAR(450) NOT NULL,
    last_update_utc NVARCHAR(450) NOT NULL,
    CONSTRAINT FK_objective_refinement_messages_session FOREIGN KEY (objective_refinement_session_id) REFERENCES objective_refinement_sessions(id) ON DELETE CASCADE,
    CONSTRAINT FK_objective_refinement_messages_objective FOREIGN KEY (objective_id) REFERENCES objectives(id),
    CONSTRAINT FK_objective_refinement_messages_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT FK_objective_refinement_messages_user FOREIGN KEY (user_id) REFERENCES users(id)
);",
            @"CREATE INDEX idx_objective_refinement_messages_session_sequence ON objective_refinement_messages(objective_refinement_session_id, sequence);",
            @"CREATE INDEX idx_objective_refinement_messages_objective_created ON objective_refinement_messages(objective_id, created_utc DESC);",
        };
    }
}
