namespace Armada.Test.Unit.Suites.Routes
{
    using System;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Text.Json;
    using System.Threading.Tasks;
    using Armada.Core;
    using Armada.Core.Database;
    using Armada.Core.Enums;
    using Armada.Core.Models;
    using Armada.Core.Services;
    using Armada.Core.Settings;
    using Armada.Server.Mcp.Tools;
    using Armada.Server.WebSocket;
    using Armada.Test.Common;
    using Armada.Test.Unit.TestHelpers;
    using SyslogLogging;

    /// <summary>
    /// A captain create or update request must never set a server-owned field (state, assignment,
    /// process, recovery, heartbeat, quarantine, identity or timestamps). Every write surface refuses
    /// such a request by name, and the operator tools that own captain state keep working.
    /// </summary>
    public sealed class CaptainServerOwnedFieldTests : TestSuite
    {
        /// <summary>Suite name.</summary>
        public override string Name => "Captain Server-Owned Fields";

        private static readonly JsonSerializerOptions _ServerJsonOptions = new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase
        };

        /// <summary>Run all tests.</summary>
        protected override async Task RunTestsAsync()
        {
            await RunTest("Every writable captain property is either caller-settable or server-owned, never both", () =>
            {
                HashSet<string> settable = new HashSet<string>(CaptainInputMapping.CallerSettableFieldNames, StringComparer.Ordinal);
                HashSet<string> owned = new HashSet<string>(CaptainInputMapping.ServerOwnedFieldNames, StringComparer.Ordinal);
                foreach (PropertyInfo property in typeof(Captain).GetProperties(BindingFlags.Instance | BindingFlags.Public))
                {
                    if (!property.CanWrite) continue;
                    bool inSettable = settable.Contains(property.Name);
                    bool inOwned = owned.Contains(property.Name);
                    AssertTrue(inSettable ^ inOwned, "Captain." + property.Name + " must be classified exactly once (settable=" + inSettable + ", owned=" + inOwned + ")");
                }

                HashSet<string> requestFields = new HashSet<string>(StringComparer.Ordinal);
                foreach (PropertyInfo property in typeof(CaptainServerOwnedFields).GetProperties(BindingFlags.Instance | BindingFlags.Public))
                    requestFields.Add(property.Name);
                AssertTrue(requestFields.SetEquals(owned), "The request model reads exactly the server-owned fields");
            });

            await RunTest("ForCreate takes configuration from the request and starts every server-owned field at its default", () =>
            {
                Captain input = BuildCaptainWithEveryField("request", CaptainStateEnum.Working);
                Captain created = CaptainInputMapping.ForCreate(input);

                AssertConfigurationEqual(input, created);
                Captain defaults = new Captain();
                AssertFalse(String.Equals(input.Id, created.Id, StringComparison.Ordinal), "Id is generated by the server");
                AssertEqual(defaults.TenantId, created.TenantId, "TenantId");
                AssertEqual(defaults.UserId, created.UserId, "UserId");
                AssertEqual(CaptainStateEnum.Idle, created.State, "State");
                AssertNull(created.CurrentMissionId, "CurrentMissionId");
                AssertNull(created.CurrentDockId, "CurrentDockId");
                AssertNull(created.ProcessId, "ProcessId");
                AssertEqual(0, created.RecoveryAttempts, "RecoveryAttempts");
                AssertNull(created.LastHeartbeatUtc, "LastHeartbeatUtc");
                AssertNull(created.LastProcessAliveUtc, "LastProcessAliveUtc");
                AssertNull(created.QuarantineUntilUtc, "QuarantineUntilUtc");
                AssertNull(created.QuarantineReason, "QuarantineReason");
            });

            await RunTest("ForUpdate takes configuration from the request and keeps every server-owned field of the stored captain", () =>
            {
                Captain existing = BuildCaptainWithEveryField("stored", CaptainStateEnum.Quarantined);
                Captain input = BuildCaptainWithEveryField("request", CaptainStateEnum.Working);
                Captain updated = CaptainInputMapping.ForUpdate(existing, input);

                AssertConfigurationEqual(input, updated);
                foreach (string field in CaptainInputMapping.ServerOwnedFieldNames)
                {
                    if (field == nameof(Captain.LastUpdateUtc)) continue;
                    object? expected = typeof(Captain).GetProperty(field)!.GetValue(existing);
                    object? actual = typeof(Captain).GetProperty(field)!.GetValue(updated);
                    AssertEqual(expected, actual, field + " is kept from the stored captain");
                }
                AssertTrue(updated.LastUpdateUtc > existing.LastUpdateUtc, "LastUpdateUtc is refreshed");
            });

            await RunTest("A request that repeats the stored server-owned values is not a write", () =>
            {
                Captain existing = BuildCaptainWithEveryField("stored", CaptainStateEnum.Quarantined);
                CaptainServerOwnedFields echo = new CaptainServerOwnedFields
                {
                    Id = existing.Id,
                    TenantId = existing.TenantId,
                    UserId = existing.UserId,
                    State = existing.State,
                    CurrentMissionId = existing.CurrentMissionId,
                    CurrentDockId = existing.CurrentDockId,
                    ProcessId = existing.ProcessId,
                    RecoveryAttempts = existing.RecoveryAttempts,
                    LastHeartbeatUtc = existing.LastHeartbeatUtc,
                    LastProcessAliveUtc = existing.LastProcessAliveUtc,
                    QuarantineUntilUtc = existing.QuarantineUntilUtc,
                    QuarantineReason = existing.QuarantineReason,
                    CreatedUtc = existing.CreatedUtc,
                    LastUpdateUtc = existing.LastUpdateUtc
                };
                AssertNull(CaptainInputMapping.FindServerOwnedFieldViolation(echo, existing), "Echoed stored values");
                AssertNull(CaptainInputMapping.FindServerOwnedFieldViolation(new CaptainServerOwnedFields(), null), "An empty request");
                AssertNull(CaptainInputMapping.FindServerOwnedFieldViolation(null, existing), "An absent request");
            });

            await RunTest("A client request body built from a whole captain carries configuration only and is accepted", () =>
            {
                Captain whole = BuildCaptainWithEveryField("request", CaptainStateEnum.Working);
                Dictionary<string, object?> body = CaptainInputMapping.ToRequestBody(whole);

                AssertTrue(new HashSet<string>(body.Keys, StringComparer.Ordinal).SetEquals(CaptainInputMapping.CallerSettableFieldNames),
                    "The body carries exactly the caller-settable fields");
                string json = JsonSerializer.Serialize(body);
                CaptainServerOwnedFields? submitted = JsonSerializer.Deserialize<CaptainServerOwnedFields>(json, _ServerJsonOptions);
                AssertNull(CaptainInputMapping.FindServerOwnedFieldViolation(submitted, null), "A create sent through the client body is not refused");
                Captain? parsed = JsonSerializer.Deserialize<Captain>(json, _ServerJsonOptions);
                AssertConfigurationEqual(whole, parsed!);
            });

            await RunTest("Every server-owned field sent with a changed value is named in one refusal", () =>
            {
                Captain existing = BuildCaptainWithEveryField("stored", CaptainStateEnum.Idle);
                DateTime later = DateTime.UtcNow.AddDays(3);
                CaptainServerOwnedFields changed = new CaptainServerOwnedFields
                {
                    Id = "cpt_other",
                    TenantId = "tenant-other",
                    UserId = "user-other",
                    State = CaptainStateEnum.Working,
                    CurrentMissionId = "msn_other",
                    CurrentDockId = "dck_other",
                    ProcessId = 999,
                    ProcessStartedUtc = later,
                    RecoveryAttempts = 9,
                    LastHeartbeatUtc = later,
                    LastProcessAliveUtc = later,
                    QuarantineUntilUtc = later,
                    QuarantineReason = "other",
                    CreatedUtc = later,
                    LastUpdateUtc = later
                };

                string? error = CaptainInputMapping.FindServerOwnedFieldViolation(changed, existing);
                AssertNotNull(error, "The refusal");
                AssertStartsWith(CaptainInputMapping.ServerOwnedFieldErrorCode + ":", error!);
                foreach (string field in CaptainInputMapping.ServerOwnedFieldNames)
                    AssertContains(field, error!, field + " is named");
            });

            await RunTest("Mcp create with State and quarantine fields is refused by name and persists nothing", async () =>
            {
                using (TestDatabase testDb = await TestDatabaseHelper.CreateDatabaseAsync().ConfigureAwait(false))
                {
                    Dictionary<string, Func<JsonElement?, Task<object>>> tools = RegisterMcpTools(testDb.Driver);
                    JsonElement args = JsonSerializer.SerializeToElement(new
                    {
                        name = "mcp-owned-create",
                        state = "Working",
                        quarantineReason = "caller supplied",
                        quarantineUntilUtc = "2099-01-01T00:00:00Z"
                    });

                    string resultJson = JsonSerializer.Serialize(await tools["armada_create_captain"](args).ConfigureAwait(false));

                    AssertContains("\"content\"", resultJson, "A server-owned field must return the MCP tool error envelope");
                    AssertContains("State", resultJson, "The refusal names State");
                    AssertContains("QuarantineReason", resultJson, "The refusal names QuarantineReason");
                    AssertContains("QuarantineUntilUtc", resultJson, "The refusal names QuarantineUntilUtc");
                    Captain? persisted = await testDb.Driver.Captains.ReadByNameAsync("mcp-owned-create").ConfigureAwait(false);
                    AssertNull(persisted, "A refused create must not persist a captain");
                }
            });

            await RunTest("Mcp create with default server-owned values is accepted as Idle", async () =>
            {
                using (TestDatabase testDb = await TestDatabaseHelper.CreateDatabaseAsync().ConfigureAwait(false))
                {
                    Dictionary<string, Func<JsonElement?, Task<object>>> tools = RegisterMcpTools(testDb.Driver);
                    JsonElement args = JsonSerializer.SerializeToElement(new
                    {
                        name = "mcp-default-create",
                        state = "Idle",
                        recoveryAttempts = 0
                    });

                    string resultJson = JsonSerializer.Serialize(await tools["armada_create_captain"](args).ConfigureAwait(false));

                    AssertFalse(resultJson.Contains("\"content\"", StringComparison.Ordinal), "Default values are not a server-owned write: " + resultJson);
                    Captain? persisted = await testDb.Driver.Captains.ReadByNameAsync("mcp-default-create").ConfigureAwait(false);
                    AssertNotNull(persisted, "The captain is created");
                    AssertEqual(CaptainStateEnum.Idle, persisted!.State);
                }
            });

            await RunTest("Mcp update with State is refused by name and leaves the captain unchanged", async () =>
            {
                using (TestDatabase testDb = await TestDatabaseHelper.CreateDatabaseAsync().ConfigureAwait(false))
                {
                    Captain captain = await testDb.Driver.Captains.CreateAsync(new Captain("mcp-owned-update")).ConfigureAwait(false);
                    Dictionary<string, Func<JsonElement?, Task<object>>> tools = RegisterMcpTools(testDb.Driver);
                    JsonElement args = JsonSerializer.SerializeToElement(new
                    {
                        captainId = captain.Id,
                        name = "mcp-owned-update-renamed",
                        state = "Working",
                        currentMissionId = "msn_caller_supplied"
                    });

                    string resultJson = JsonSerializer.Serialize(await tools["armada_update_captain"](args).ConfigureAwait(false));

                    AssertContains("\"content\"", resultJson, "A server-owned field must return the MCP tool error envelope");
                    AssertContains("State", resultJson, "The refusal names State");
                    AssertContains("CurrentMissionId", resultJson, "The refusal names CurrentMissionId");
                    Captain? persisted = await testDb.Driver.Captains.ReadAsync(captain.Id).ConfigureAwait(false);
                    AssertEqual("mcp-owned-update", persisted!.Name, "A refused update writes nothing");
                    AssertEqual(CaptainStateEnum.Idle, persisted.State);
                    AssertNull(persisted.CurrentMissionId, "CurrentMissionId");
                }
            });

            await RunTest("Mcp bench, config update and unbench keep owning captain state", async () =>
            {
                using (TestDatabase testDb = await TestDatabaseHelper.CreateDatabaseAsync().ConfigureAwait(false))
                {
                    Captain captain = await testDb.Driver.Captains.CreateAsync(new Captain("mcp-bench-flow")).ConfigureAwait(false);
                    Dictionary<string, Func<JsonElement?, Task<object>>> tools = RegisterMcpTools(testDb.Driver);

                    string benchJson = JsonSerializer.Serialize(await tools["armada_bench_captain"](JsonSerializer.SerializeToElement(new
                    {
                        captainId = captain.Id,
                        reason = "provider out of balance",
                        durationMinutes = 30
                    })).ConfigureAwait(false));
                    AssertContains("benched", benchJson, "Bench succeeds");

                    string updateJson = JsonSerializer.Serialize(await tools["armada_update_captain"](JsonSerializer.SerializeToElement(new
                    {
                        captainId = captain.Id,
                        name = "mcp-bench-flow-renamed"
                    })).ConfigureAwait(false));
                    AssertFalse(updateJson.Contains("\"content\"", StringComparison.Ordinal), "A config-only update of a benched captain is accepted: " + updateJson);

                    Captain? benched = await testDb.Driver.Captains.ReadAsync(captain.Id).ConfigureAwait(false);
                    AssertEqual("mcp-bench-flow-renamed", benched!.Name);
                    AssertEqual(CaptainStateEnum.Quarantined, benched.State);
                    AssertEqual("provider out of balance", benched.QuarantineReason);
                    AssertNotNull(benched.QuarantineUntilUtc, "The bench expiry survives a config update");

                    string unbenchJson = JsonSerializer.Serialize(await tools["armada_unbench_captain"](JsonSerializer.SerializeToElement(new
                    {
                        captainId = captain.Id
                    })).ConfigureAwait(false));
                    AssertContains("restored", unbenchJson, "Unbench succeeds");
                    Captain? restored = await testDb.Driver.Captains.ReadAsync(captain.Id).ConfigureAwait(false);
                    AssertEqual(CaptainStateEnum.Idle, restored!.State);
                    AssertNull(restored.QuarantineReason, "QuarantineReason is cleared by unbench");
                }
            });

            await RunTest("WebSocket create with State and quarantine fields is refused by name and persists nothing", async () =>
            {
                using (TestDatabase testDb = await TestDatabaseHelper.CreateDatabaseAsync().ConfigureAwait(false))
                {
                    WebSocketCommandHandler handler = CreateWebSocketHandler(testDb.Driver);
                    string rawBody = JsonSerializer.Serialize(new
                    {
                        Route = "command",
                        action = "create_captain",
                        data = new
                        {
                            Name = "ws-owned-create",
                            State = "Working",
                            ProcessId = 4242,
                            QuarantineReason = "caller supplied"
                        }
                    });

                    string resultJson = JsonSerializer.Serialize(await handler.HandleCommandAsync(
                        "create_captain", new WebSocketCommand { Action = "create_captain" }, rawBody, McpTestCaller.Operator).ConfigureAwait(false));

                    AssertContains("command.error", resultJson, "A server-owned field is refused");
                    AssertContains("State", resultJson, "The refusal names State");
                    AssertContains("ProcessId", resultJson, "The refusal names ProcessId");
                    AssertContains("QuarantineReason", resultJson, "The refusal names QuarantineReason");
                    Captain? persisted = await testDb.Driver.Captains.ReadByNameAsync("ws-owned-create").ConfigureAwait(false);
                    AssertNull(persisted, "A refused create must not persist a captain");
                }
            });

            await RunTest("WebSocket update with State is refused by name and leaves the captain unchanged", async () =>
            {
                using (TestDatabase testDb = await TestDatabaseHelper.CreateDatabaseAsync().ConfigureAwait(false))
                {
                    Captain captain = await testDb.Driver.Captains.CreateAsync(new Captain("ws-owned-update")).ConfigureAwait(false);
                    WebSocketCommandHandler handler = CreateWebSocketHandler(testDb.Driver);
                    string rawBody = JsonSerializer.Serialize(new
                    {
                        Route = "command",
                        action = "update_captain",
                        id = captain.Id,
                        data = new { Name = "ws-owned-update-renamed", State = "Working" }
                    });

                    string resultJson = JsonSerializer.Serialize(await handler.HandleCommandAsync(
                        "update_captain", new WebSocketCommand { Action = "update_captain", Id = captain.Id }, rawBody, McpTestCaller.Operator).ConfigureAwait(false));

                    AssertContains("command.error", resultJson, "A server-owned field is refused");
                    AssertContains("State", resultJson, "The refusal names State");
                    Captain? persisted = await testDb.Driver.Captains.ReadAsync(captain.Id).ConfigureAwait(false);
                    AssertEqual("ws-owned-update", persisted!.Name, "A refused update writes nothing");
                    AssertEqual(CaptainStateEnum.Idle, persisted.State);
                }
            });

            await RunTest("WebSocket config update keeps the quarantine, tenant and liveness of the stored captain", async () =>
            {
                using (TestDatabase testDb = await TestDatabaseHelper.CreateDatabaseAsync().ConfigureAwait(false))
                {
                    DateTime until = DateTime.UtcNow.AddHours(1);
                    Captain captain = new Captain("ws-quarantine-keep");
                    captain.TenantId = Constants.DefaultTenantId;
                    captain.UserId = Constants.DefaultUserId;
                    captain.State = CaptainStateEnum.Quarantined;
                    captain.QuarantineReason = "operator hold";
                    captain.QuarantineUntilUtc = until;
                    captain = await testDb.Driver.Captains.CreateAsync(captain).ConfigureAwait(false);
                    await testDb.Driver.Captains.UpdateProcessAliveAsync(captain.Id).ConfigureAwait(false);
                    WebSocketCommandHandler handler = CreateWebSocketHandler(testDb.Driver);
                    string rawBody = JsonSerializer.Serialize(new
                    {
                        Route = "command",
                        action = "update_captain",
                        id = captain.Id,
                        data = new { Name = "ws-quarantine-keep-renamed", Runtime = "ClaudeCode" }
                    });

                    string resultJson = JsonSerializer.Serialize(await handler.HandleCommandAsync(
                        "update_captain", new WebSocketCommand { Action = "update_captain", Id = captain.Id }, rawBody, McpTestCaller.Operator).ConfigureAwait(false));

                    AssertContains("command.result", resultJson, "A config-only update is accepted");
                    Captain? persisted = await testDb.Driver.Captains.ReadAsync(captain.Id).ConfigureAwait(false);
                    AssertEqual("ws-quarantine-keep-renamed", persisted!.Name);
                    AssertEqual(CaptainStateEnum.Quarantined, persisted.State);
                    AssertEqual("operator hold", persisted.QuarantineReason, "QuarantineReason survives a config update");
                    AssertNotNull(persisted.QuarantineUntilUtc, "QuarantineUntilUtc survives a config update");
                    AssertEqual(Constants.DefaultTenantId, persisted.TenantId, "TenantId survives a config update");
                    AssertEqual(Constants.DefaultUserId, persisted.UserId, "UserId survives a config update");
                    AssertNotNull(persisted.LastProcessAliveUtc, "LastProcessAliveUtc survives a config update");
                }
            });
        }

        private static Captain BuildCaptainWithEveryField(string tag, CaptainStateEnum state)
        {
            DateTime stamp = tag == "stored" ? DateTime.UtcNow.AddDays(-2) : DateTime.UtcNow.AddDays(-1);
            Captain captain = new Captain(tag + "-captain", tag == "stored" ? AgentRuntimeEnum.Codex : AgentRuntimeEnum.Mux);
            captain.TenantId = tag + "-tenant";
            captain.UserId = tag + "-user";
            captain.Model = tag + "-model";
            captain.ModelEndpointId = tag + "-endpoint";
            captain.ApiKey = tag + "-key";
            captain.ApiBaseUrl = "https://" + tag + ".example.test";
            captain.SystemInstructions = tag + " instructions";
            captain.AllowedPersonas = "[\"" + tag + "\"]";
            captain.PreferredPersona = tag + "-persona";
            captain.RuntimeOptionsJson = "{\"tag\":\"" + tag + "\"}";
            captain.Tier = tag == "stored" ? CaptainTierEnum.Standard : CaptainTierEnum.Premium;
            captain.PreferenceRank = tag == "stored" ? 1 : 2;
            captain.DefaultPlaybooks = "[]" + tag;
            captain.State = state;
            captain.CurrentMissionId = "msn_" + tag;
            captain.CurrentDockId = "dck_" + tag;
            captain.ProcessId = tag == "stored" ? 111 : 222;
            captain.RecoveryAttempts = tag == "stored" ? 1 : 2;
            captain.LastHeartbeatUtc = stamp;
            captain.LastProcessAliveUtc = stamp.AddSeconds(1);
            captain.QuarantineUntilUtc = stamp.AddHours(5);
            captain.QuarantineReason = tag + " reason";
            captain.CreatedUtc = stamp.AddHours(-1);
            captain.LastUpdateUtc = stamp;
            return captain;
        }

        private void AssertConfigurationEqual(Captain expected, Captain actual)
        {
            foreach (string field in CaptainInputMapping.CallerSettableFieldNames)
            {
                object? expectedValue = typeof(Captain).GetProperty(field)!.GetValue(expected);
                object? actualValue = typeof(Captain).GetProperty(field)!.GetValue(actual);
                AssertEqual(expectedValue, actualValue, field + " is taken from the request");
            }
        }

        private static Dictionary<string, Func<JsonElement?, Task<object>>> RegisterMcpTools(DatabaseDriver database)
        {
            Dictionary<string, Func<JsonElement?, Task<object>>> tools = new Dictionary<string, Func<JsonElement?, Task<object>>>(StringComparer.Ordinal);
            LoggingModule logging = new LoggingModule();
            logging.Settings.EnableConsole = false;
            ArmadaSettings settings = new ArmadaSettings();
            CaptainQuarantineService quarantine = new CaptainQuarantineService(database, settings, logging);
            McpCaptainTools.Register(
                (name, _, _, handler) => tools[name] = Armada.Test.Unit.TestHelpers.McpTestCaller.Wrap(handler),
                database,
                null!,
                settings,
                null,
                null,
                logging,
                quarantine);
            return tools;
        }

        private static WebSocketCommandHandler CreateWebSocketHandler(DatabaseDriver database)
        {
            return new WebSocketCommandHandler(
                null!,
                database,
                null!,
                null,
                null,
                null,
                _ServerJsonOptions,
                mission => { },
                voyage => { });
        }
    }
}
