namespace Armada.Core.Database.Mysql.Queries
{
    /// <summary>
    /// Additive workflow and objective prerequisites omitted from server history.
    /// </summary>
    internal static class ForkOperationalSchema
    {
        internal static readonly string[] Statements = new string[]
        {
            @"ALTER TABLE vessels ADD COLUMN github_token_override LONGTEXT;",
            @"CREATE TABLE request_history (
                        id VARCHAR(450) NOT NULL PRIMARY KEY,
                        tenant_id VARCHAR(450),
                        user_id VARCHAR(450),
                        credential_id VARCHAR(450),
                        principal_display LONGTEXT,
                        auth_method LONGTEXT,
                        method LONGTEXT NOT NULL,
                        route VARCHAR(450) NOT NULL,
                        route_template LONGTEXT,
                        query_string LONGTEXT,
                        status_code INT NOT NULL,
                        duration_ms DOUBLE NOT NULL DEFAULT 0,
                        request_size_bytes BIGINT NOT NULL DEFAULT 0,
                        response_size_bytes BIGINT NOT NULL DEFAULT 0,
                        request_content_type LONGTEXT,
                        response_content_type LONGTEXT,
                        is_success TINYINT(1) NOT NULL DEFAULT 0,
                        client_ip LONGTEXT,
                        correlation_id VARCHAR(450),
                        created_utc DATETIME(6) NOT NULL
                    );",
            @"CREATE TABLE request_history_detail (
                        request_history_id VARCHAR(450) NOT NULL PRIMARY KEY,
                        path_params_json LONGTEXT,
                        query_params_json LONGTEXT,
                        request_headers_json LONGTEXT,
                        response_headers_json LONGTEXT,
                        request_body_text LONGTEXT,
                        response_body_text LONGTEXT,
                        request_body_truncated TINYINT(1) NOT NULL DEFAULT 0,
                        response_body_truncated TINYINT(1) NOT NULL DEFAULT 0,
                        FOREIGN KEY (request_history_id) REFERENCES request_history(id) ON DELETE CASCADE
                    );",
            @"CREATE TABLE workflow_profiles (
                        id VARCHAR(450) NOT NULL PRIMARY KEY,
                        tenant_id VARCHAR(450),
                        user_id VARCHAR(450),
                        name LONGTEXT NOT NULL,
                        description LONGTEXT,
                        scope VARCHAR(450) NOT NULL DEFAULT 'Global',
                        fleet_id VARCHAR(450),
                        vessel_id VARCHAR(450),
                        is_default TINYINT(1) NOT NULL DEFAULT 0,
                        active TINYINT(1) NOT NULL DEFAULT 1,
                        language_hints_json LONGTEXT NOT NULL DEFAULT ('[]'),
                        environment_variables_json LONGTEXT,
                        lint_command LONGTEXT,
                        build_command LONGTEXT,
                        unit_test_command LONGTEXT,
                        containerless_unit_test_command LONGTEXT,
                        integration_test_command LONGTEXT,
                        e2e_test_command LONGTEXT,
                        package_command LONGTEXT,
                        publish_artifact_command LONGTEXT,
                        release_versioning_command LONGTEXT,
                        changelog_generation_command LONGTEXT,
                        migration_command LONGTEXT,
                        security_scan_command LONGTEXT,
                        performance_command LONGTEXT,
                        deployment_verification_command LONGTEXT,
                        rollback_verification_command LONGTEXT,
                        required_secrets_json LONGTEXT NOT NULL DEFAULT ('[]'),
                        expected_artifacts_json LONGTEXT NOT NULL DEFAULT ('[]'),
                        environments_json LONGTEXT NOT NULL DEFAULT ('[]'),
                        created_utc DATETIME(6) NOT NULL,
                        last_update_utc DATETIME(6) NOT NULL
                    );",
            @"CREATE TABLE check_runs (
                        id VARCHAR(450) NOT NULL PRIMARY KEY,
                        tenant_id VARCHAR(450),
                        user_id VARCHAR(450),
                        workflow_profile_id VARCHAR(450),
                        vessel_id VARCHAR(450),
                        mission_id VARCHAR(450),
                        voyage_id VARCHAR(450),
                        deployment_id VARCHAR(450),
                        label LONGTEXT,
                        check_type LONGTEXT NOT NULL,
                        status VARCHAR(450) NOT NULL,
                        source LONGTEXT NOT NULL,
                        provider_name LONGTEXT,
                        external_id VARCHAR(450),
                        external_url LONGTEXT,
                        environment_name LONGTEXT,
                        command LONGTEXT NOT NULL,
                        working_directory LONGTEXT,
                        branch_name LONGTEXT,
                        commit_hash LONGTEXT,
                        exit_code INT,
                        output LONGTEXT,
                        summary LONGTEXT,
                        test_summary_json LONGTEXT,
                        coverage_summary_json LONGTEXT,
                        artifacts_json LONGTEXT NOT NULL DEFAULT ('[]'),
                        duration_ms BIGINT,
                        started_utc DATETIME(6),
                        completed_utc DATETIME(6),
                        created_utc DATETIME(6) NOT NULL,
                        last_update_utc DATETIME(6) NOT NULL
                    );",
            @"CREATE TABLE environments (
                        id VARCHAR(450) NOT NULL PRIMARY KEY,
                        tenant_id VARCHAR(450),
                        user_id VARCHAR(450),
                        vessel_id VARCHAR(450),
                        name LONGTEXT NOT NULL,
                        description LONGTEXT,
                        kind VARCHAR(450) NOT NULL,
                        configuration_source LONGTEXT,
                        base_url LONGTEXT,
                        health_endpoint LONGTEXT,
                        access_notes LONGTEXT,
                        deployment_rules LONGTEXT,
                        verification_definitions_json LONGTEXT NOT NULL DEFAULT ('[]'),
                        rollout_monitoring_window_minutes INT NOT NULL DEFAULT 0,
                        rollout_monitoring_interval_seconds INT NOT NULL DEFAULT 300,
                        alert_on_regression TINYINT(1) NOT NULL DEFAULT 1,
                        requires_approval TINYINT(1) NOT NULL DEFAULT 0,
                        is_default TINYINT(1) NOT NULL DEFAULT 0,
                        active TINYINT(1) NOT NULL DEFAULT 1,
                        created_utc DATETIME(6) NOT NULL,
                        last_update_utc DATETIME(6) NOT NULL
                    );",
            @"CREATE TABLE releases (
                        id VARCHAR(450) NOT NULL PRIMARY KEY,
                        tenant_id VARCHAR(450),
                        user_id VARCHAR(450),
                        vessel_id VARCHAR(450),
                        workflow_profile_id VARCHAR(450),
                        title LONGTEXT NOT NULL,
                        version LONGTEXT,
                        tag_name LONGTEXT,
                        summary LONGTEXT,
                        notes LONGTEXT,
                        status VARCHAR(450) NOT NULL,
                        voyage_ids_json LONGTEXT NOT NULL DEFAULT ('[]'),
                        mission_ids_json LONGTEXT NOT NULL DEFAULT ('[]'),
                        check_run_ids_json LONGTEXT NOT NULL DEFAULT ('[]'),
                        artifacts_json LONGTEXT NOT NULL DEFAULT ('[]'),
                        created_utc DATETIME(6) NOT NULL,
                        last_update_utc DATETIME(6) NOT NULL,
                        published_utc DATETIME(6)
                    );",
            @"CREATE TABLE deployments (
                        id VARCHAR(450) NOT NULL PRIMARY KEY,
                        tenant_id VARCHAR(450),
                        user_id VARCHAR(450),
                        vessel_id VARCHAR(450),
                        workflow_profile_id VARCHAR(450),
                        environment_id VARCHAR(450),
                        environment_name LONGTEXT,
                        release_id VARCHAR(450),
                        mission_id VARCHAR(450),
                        voyage_id VARCHAR(450),
                        title LONGTEXT NOT NULL,
                        source_ref LONGTEXT,
                        summary LONGTEXT,
                        notes LONGTEXT,
                        status VARCHAR(450) NOT NULL,
                        verification_status LONGTEXT NOT NULL,
                        approval_required TINYINT(1) NOT NULL DEFAULT 0,
                        approved_by_user_id VARCHAR(450),
                        approved_utc DATETIME(6),
                        approval_comment LONGTEXT,
                        deploy_check_run_id VARCHAR(450),
                        smoke_test_check_run_id VARCHAR(450),
                        health_check_run_id VARCHAR(450),
                        deployment_verification_check_run_id VARCHAR(450),
                        rollback_check_run_id VARCHAR(450),
                        rollback_verification_check_run_id VARCHAR(450),
                        check_run_ids_json LONGTEXT NOT NULL DEFAULT ('[]'),
                        request_history_summary_json LONGTEXT,
                        created_utc DATETIME(6) NOT NULL,
                        started_utc DATETIME(6),
                        completed_utc DATETIME(6),
                        verified_utc DATETIME(6),
                        rolled_back_utc DATETIME(6),
                        monitoring_window_ends_utc DATETIME(6),
                        last_monitored_utc DATETIME(6),
                        last_regression_alert_utc DATETIME(6),
                        latest_monitoring_summary LONGTEXT,
                        monitoring_failure_count INT NOT NULL DEFAULT 0,
                        last_update_utc DATETIME(6) NOT NULL
                    );",
            @"CREATE INDEX idx_request_history_tenant_created ON request_history(tenant_id, created_utc DESC);",
            @"CREATE INDEX idx_request_history_user_created ON request_history(user_id, created_utc DESC);",
            @"CREATE INDEX idx_request_history_route_created ON request_history(route, created_utc DESC);",
            @"CREATE INDEX idx_workflow_profiles_tenant_scope ON workflow_profiles(tenant_id, scope);",
            @"CREATE INDEX idx_workflow_profiles_fleet ON workflow_profiles(fleet_id);",
            @"CREATE INDEX idx_workflow_profiles_vessel ON workflow_profiles(vessel_id);",
            @"CREATE INDEX idx_check_runs_tenant_created ON check_runs(tenant_id, created_utc DESC);",
            @"CREATE INDEX idx_check_runs_vessel_created ON check_runs(vessel_id, created_utc DESC);",
            @"CREATE INDEX idx_check_runs_mission_created ON check_runs(mission_id, created_utc DESC);",
            @"CREATE INDEX idx_check_runs_deployment_created ON check_runs(deployment_id, created_utc DESC);",
            @"CREATE INDEX idx_environments_tenant_vessel ON environments(tenant_id, vessel_id);",
            @"CREATE INDEX idx_environments_vessel_kind ON environments(vessel_id, kind);",
            @"CREATE INDEX idx_releases_tenant_created ON releases(tenant_id, created_utc DESC);",
            @"CREATE INDEX idx_releases_vessel_created ON releases(vessel_id, created_utc DESC);",
            @"CREATE INDEX idx_releases_status_created ON releases(status, created_utc DESC);",
            @"CREATE INDEX idx_deployments_tenant_created ON deployments(tenant_id, created_utc DESC);",
            @"CREATE INDEX idx_deployments_vessel_created ON deployments(vessel_id, created_utc DESC);",
            @"CREATE INDEX idx_deployments_status_created ON deployments(status, created_utc DESC);",
            @"CREATE INDEX idx_deployments_environment_created ON deployments(environment_id, created_utc DESC);",
            @"CREATE TABLE objectives (
    id VARCHAR(450) NOT NULL PRIMARY KEY,
    tenant_id VARCHAR(450),
    user_id VARCHAR(450),
    title VARCHAR(450) NOT NULL,
    description LONGTEXT,
    status VARCHAR(64) NOT NULL DEFAULT 'Draft',
    kind VARCHAR(64) NOT NULL DEFAULT 'Feature',
    category VARCHAR(450),
    priority VARCHAR(64) NOT NULL DEFAULT 'P2',
    `rank` INT NOT NULL DEFAULT 0,
    backlog_state VARCHAR(64) NOT NULL DEFAULT 'Inbox',
    effort VARCHAR(64) NOT NULL DEFAULT 'M',
    owner VARCHAR(450),
    target_version VARCHAR(450),
    due_utc DATETIME(6) NULL,
    parent_objective_id VARCHAR(450),
    blocked_by_objective_ids_json LONGTEXT,
    refinement_summary LONGTEXT,
    suggested_pipeline_id VARCHAR(450),
    suggested_playbooks_json LONGTEXT,
    tags_json LONGTEXT,
    acceptance_criteria_json LONGTEXT,
    non_goals_json LONGTEXT,
    rollout_constraints_json LONGTEXT,
    evidence_links_json LONGTEXT,
    fleet_ids_json LONGTEXT,
    vessel_ids_json LONGTEXT,
    planning_session_ids_json LONGTEXT,
    refinement_session_ids_json LONGTEXT,
    voyage_ids_json LONGTEXT,
    mission_ids_json LONGTEXT,
    check_run_ids_json LONGTEXT,
    release_ids_json LONGTEXT,
    deployment_ids_json LONGTEXT,
    incident_ids_json LONGTEXT,
    source_provider VARCHAR(450),
    source_type VARCHAR(450),
    source_id VARCHAR(450),
    source_url LONGTEXT,
    source_updated_utc DATETIME(6) NULL,
    created_utc DATETIME(6) NOT NULL,
    last_update_utc DATETIME(6) NOT NULL,
    completed_utc DATETIME(6) NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (parent_objective_id) REFERENCES objectives(id) ON DELETE SET NULL,
    FOREIGN KEY (suggested_pipeline_id) REFERENCES pipelines(id) ON DELETE SET NULL
);",
            @"CREATE INDEX idx_objectives_tenant_status_updated ON objectives(tenant_id, status, last_update_utc DESC);",
            @"CREATE INDEX idx_objectives_tenant_backlog_priority_rank ON objectives(tenant_id, backlog_state, priority, `rank`);",
            @"CREATE INDEX idx_objectives_tenant_kind_priority ON objectives(tenant_id, kind, priority);",
            @"CREATE INDEX idx_objectives_tenant_owner ON objectives(tenant_id(128), owner(128));",
            @"CREATE INDEX idx_objectives_tenant_due ON objectives(tenant_id, due_utc);",
            @"CREATE INDEX idx_objectives_tenant_target_version ON objectives(tenant_id(128), target_version(128));",
            @"CREATE INDEX idx_objectives_tenant_parent ON objectives(tenant_id(128), parent_objective_id(128));",
            @"CREATE INDEX idx_objectives_tenant_source ON objectives(tenant_id(128), source_provider(64), source_type(64), source_id(128));",
            @"CREATE TABLE objective_refinement_sessions (
    id VARCHAR(450) NOT NULL PRIMARY KEY,
    objective_id VARCHAR(450) NOT NULL,
    tenant_id VARCHAR(450),
    user_id VARCHAR(450),
    captain_id VARCHAR(450),
    fleet_id VARCHAR(450),
    vessel_id VARCHAR(450),
    title VARCHAR(450) NOT NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'Created',
    process_id INT NULL,
    failure_reason LONGTEXT,
    created_utc DATETIME(6) NOT NULL,
    started_utc DATETIME(6) NULL,
    completed_utc DATETIME(6) NULL,
    last_update_utc DATETIME(6) NOT NULL,
    FOREIGN KEY (objective_id) REFERENCES objectives(id) ON DELETE CASCADE,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (captain_id) REFERENCES captains(id) ON DELETE SET NULL,
    FOREIGN KEY (fleet_id) REFERENCES fleets(id) ON DELETE SET NULL,
    FOREIGN KEY (vessel_id) REFERENCES vessels(id) ON DELETE SET NULL
);",
            @"CREATE INDEX idx_objective_refinement_sessions_tenant_objective_created
    ON objective_refinement_sessions(tenant_id(128), objective_id(128), created_utc DESC);",
            @"CREATE INDEX idx_objective_refinement_sessions_tenant_captain_status
    ON objective_refinement_sessions(tenant_id(128), captain_id(128), status);",
            @"CREATE TABLE objective_refinement_messages (
    id VARCHAR(450) NOT NULL PRIMARY KEY,
    objective_refinement_session_id VARCHAR(450) NOT NULL,
    objective_id VARCHAR(450) NOT NULL,
    tenant_id VARCHAR(450),
    user_id VARCHAR(450),
    role VARCHAR(64) NOT NULL,
    sequence INT NOT NULL,
    content LONGTEXT NOT NULL,
    is_selected TINYINT(1) NOT NULL DEFAULT 0,
    created_utc DATETIME(6) NOT NULL,
    last_update_utc DATETIME(6) NOT NULL,
    FOREIGN KEY (objective_refinement_session_id) REFERENCES objective_refinement_sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (objective_id) REFERENCES objectives(id) ON DELETE CASCADE,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);",
            @"CREATE INDEX idx_objective_refinement_messages_session_sequence
    ON objective_refinement_messages(objective_refinement_session_id, sequence);",
            @"CREATE INDEX idx_objective_refinement_messages_objective_created
    ON objective_refinement_messages(objective_id, created_utc DESC);",
        };
    }
}
