namespace Armada.Core.Database.Postgresql.Queries
{
    /// <summary>
    /// Additive prerequisites omitted from the historical server migration sequence.
    /// Applied migration declarations and ledger rows remain unchanged.
    /// </summary>
    internal static class ForkOperationalSchema
    {
        internal static readonly string[] Statements = new string[]
        {
            @"ALTER TABLE vessels ADD COLUMN github_token_override TEXT;",
            @"CREATE TABLE workflow_profiles (
                        id TEXT NOT NULL PRIMARY KEY,
                        tenant_id TEXT,
                        user_id TEXT,
                        name TEXT NOT NULL,
                        description TEXT,
                        scope TEXT NOT NULL DEFAULT 'Global',
                        fleet_id TEXT,
                        vessel_id TEXT,
                        is_default BOOLEAN NOT NULL DEFAULT FALSE,
                        active BOOLEAN NOT NULL DEFAULT TRUE,
                        language_hints_json TEXT NOT NULL DEFAULT '[]',
                        environment_variables_json TEXT,
                        lint_command TEXT,
                        build_command TEXT,
                        unit_test_command TEXT,
                        containerless_unit_test_command TEXT,
                        integration_test_command TEXT,
                        e2e_test_command TEXT,
                        package_command TEXT,
                        publish_artifact_command TEXT,
                        release_versioning_command TEXT,
                        changelog_generation_command TEXT,
                        migration_command TEXT,
                        security_scan_command TEXT,
                        performance_command TEXT,
                        deployment_verification_command TEXT,
                        rollback_verification_command TEXT,
                        required_secrets_json TEXT NOT NULL DEFAULT '[]',
                        expected_artifacts_json TEXT NOT NULL DEFAULT '[]',
                        environments_json TEXT NOT NULL DEFAULT '[]',
                        created_utc TIMESTAMPTZ NOT NULL,
                        last_update_utc TIMESTAMPTZ NOT NULL
                    );",
            @"CREATE TABLE check_runs (
                        id TEXT NOT NULL PRIMARY KEY,
                        tenant_id TEXT,
                        user_id TEXT,
                        workflow_profile_id TEXT,
                        vessel_id TEXT,
                        mission_id TEXT,
                        voyage_id TEXT,
                        deployment_id TEXT,
                        label TEXT,
                        check_type TEXT NOT NULL,
                        status TEXT NOT NULL,
                        source TEXT NOT NULL,
                        provider_name TEXT,
                        external_id TEXT,
                        external_url TEXT,
                        environment_name TEXT,
                        command TEXT NOT NULL,
                        working_directory TEXT,
                        branch_name TEXT,
                        commit_hash TEXT,
                        exit_code INTEGER,
                        output TEXT,
                        summary TEXT,
                        test_summary_json TEXT,
                        coverage_summary_json TEXT,
                        artifacts_json TEXT NOT NULL DEFAULT '[]',
                        duration_ms BIGINT,
                        started_utc TIMESTAMPTZ,
                        completed_utc TIMESTAMPTZ,
                        created_utc TIMESTAMPTZ NOT NULL,
                        last_update_utc TIMESTAMPTZ NOT NULL
                    );",
            @"CREATE TABLE environments (
                        id TEXT NOT NULL PRIMARY KEY,
                        tenant_id TEXT,
                        user_id TEXT,
                        vessel_id TEXT,
                        name TEXT NOT NULL,
                        description TEXT,
                        kind TEXT NOT NULL,
                        configuration_source TEXT,
                        base_url TEXT,
                        health_endpoint TEXT,
                        access_notes TEXT,
                        deployment_rules TEXT,
                        verification_definitions_json TEXT NOT NULL DEFAULT '[]',
                        rollout_monitoring_window_minutes INTEGER NOT NULL DEFAULT 0,
                        rollout_monitoring_interval_seconds INTEGER NOT NULL DEFAULT 300,
                        alert_on_regression BOOLEAN NOT NULL DEFAULT TRUE,
                        requires_approval BOOLEAN NOT NULL DEFAULT FALSE,
                        is_default BOOLEAN NOT NULL DEFAULT FALSE,
                        active BOOLEAN NOT NULL DEFAULT TRUE,
                        created_utc TIMESTAMPTZ NOT NULL,
                        last_update_utc TIMESTAMPTZ NOT NULL
                    );",
            @"CREATE TABLE releases (
                        id TEXT NOT NULL PRIMARY KEY,
                        tenant_id TEXT,
                        user_id TEXT,
                        vessel_id TEXT,
                        workflow_profile_id TEXT,
                        title TEXT NOT NULL,
                        version TEXT,
                        tag_name TEXT,
                        summary TEXT,
                        notes TEXT,
                        status TEXT NOT NULL,
                        voyage_ids_json TEXT NOT NULL DEFAULT '[]',
                        mission_ids_json TEXT NOT NULL DEFAULT '[]',
                        check_run_ids_json TEXT NOT NULL DEFAULT '[]',
                        artifacts_json TEXT NOT NULL DEFAULT '[]',
                        created_utc TIMESTAMPTZ NOT NULL,
                        last_update_utc TIMESTAMPTZ NOT NULL,
                        published_utc TIMESTAMPTZ
                    );",
            @"CREATE TABLE deployments (
                        id TEXT NOT NULL PRIMARY KEY,
                        tenant_id TEXT,
                        user_id TEXT,
                        vessel_id TEXT,
                        workflow_profile_id TEXT,
                        environment_id TEXT,
                        environment_name TEXT,
                        release_id TEXT,
                        mission_id TEXT,
                        voyage_id TEXT,
                        title TEXT NOT NULL,
                        source_ref TEXT,
                        summary TEXT,
                        notes TEXT,
                        status TEXT NOT NULL,
                        verification_status TEXT NOT NULL,
                        approval_required BOOLEAN NOT NULL DEFAULT FALSE,
                        approved_by_user_id TEXT,
                        approved_utc TIMESTAMPTZ,
                        approval_comment TEXT,
                        deploy_check_run_id TEXT,
                        smoke_test_check_run_id TEXT,
                        health_check_run_id TEXT,
                        deployment_verification_check_run_id TEXT,
                        rollback_check_run_id TEXT,
                        rollback_verification_check_run_id TEXT,
                        check_run_ids_json TEXT NOT NULL DEFAULT '[]',
                        request_history_summary_json TEXT,
                        created_utc TIMESTAMPTZ NOT NULL,
                        started_utc TIMESTAMPTZ,
                        completed_utc TIMESTAMPTZ,
                        verified_utc TIMESTAMPTZ,
                        rolled_back_utc TIMESTAMPTZ,
                        monitoring_window_ends_utc TIMESTAMPTZ,
                        last_monitored_utc TIMESTAMPTZ,
                        last_regression_alert_utc TIMESTAMPTZ,
                        latest_monitoring_summary TEXT,
                        monitoring_failure_count INTEGER NOT NULL DEFAULT 0,
                        last_update_utc TIMESTAMPTZ NOT NULL
                    );",
            @"CREATE INDEX idx_workflow_profiles_tenant_scope ON workflow_profiles(tenant_id, scope);",
            @"CREATE INDEX idx_workflow_profiles_fleet ON workflow_profiles(fleet_id);",
            @"CREATE INDEX idx_workflow_profiles_vessel ON workflow_profiles(vessel_id);",
            @"CREATE INDEX idx_check_runs_tenant_created ON check_runs(tenant_id, created_utc DESC);",
            @"CREATE INDEX idx_check_runs_vessel_created ON check_runs(vessel_id, created_utc DESC);",
            @"CREATE INDEX idx_check_runs_mission_created ON check_runs(mission_id, created_utc DESC);",
            @"CREATE INDEX idx_check_runs_deployment_created ON check_runs(deployment_id, created_utc DESC);",
            @"CREATE INDEX idx_environments_tenant_vessel ON environments(tenant_id, vessel_id);",
            @"CREATE INDEX idx_environments_vessel_kind ON environments(vessel_id, kind);",
            @"CREATE INDEX idx_releases_tenant_created ON releases(tenant_id, created_utc DESC);",
            @"CREATE INDEX idx_releases_vessel_created ON releases(vessel_id, created_utc DESC);",
            @"CREATE INDEX idx_releases_status_created ON releases(status, created_utc DESC);",
            @"CREATE INDEX idx_deployments_tenant_created ON deployments(tenant_id, created_utc DESC);",
            @"CREATE INDEX idx_deployments_vessel_created ON deployments(vessel_id, created_utc DESC);",
            @"CREATE INDEX idx_deployments_status_created ON deployments(status, created_utc DESC);",
            @"CREATE INDEX idx_deployments_environment_created ON deployments(environment_id, created_utc DESC);",
            @"CREATE TABLE objectives (
    id TEXT PRIMARY KEY,
    tenant_id TEXT,
    user_id TEXT,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'Draft',
    kind TEXT NOT NULL DEFAULT 'Feature',
    category TEXT,
    priority TEXT NOT NULL DEFAULT 'P2',
    rank INTEGER NOT NULL DEFAULT 0,
    backlog_state TEXT NOT NULL DEFAULT 'Inbox',
    effort TEXT NOT NULL DEFAULT 'M',
    owner TEXT,
    target_version TEXT,
    due_utc TIMESTAMP,
    parent_objective_id TEXT,
    blocked_by_objective_ids_json TEXT,
    refinement_summary TEXT,
    suggested_pipeline_id TEXT,
    suggested_playbooks_json TEXT,
    tags_json TEXT,
    acceptance_criteria_json TEXT,
    non_goals_json TEXT,
    rollout_constraints_json TEXT,
    evidence_links_json TEXT,
    fleet_ids_json TEXT,
    vessel_ids_json TEXT,
    planning_session_ids_json TEXT,
    refinement_session_ids_json TEXT,
    voyage_ids_json TEXT,
    mission_ids_json TEXT,
    check_run_ids_json TEXT,
    release_ids_json TEXT,
    deployment_ids_json TEXT,
    incident_ids_json TEXT,
    source_provider TEXT,
    source_type TEXT,
    source_id TEXT,
    source_url TEXT,
    source_updated_utc TIMESTAMP,
    created_utc TIMESTAMP NOT NULL,
    last_update_utc TIMESTAMP NOT NULL,
    completed_utc TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (parent_objective_id) REFERENCES objectives(id) ON DELETE SET NULL,
    FOREIGN KEY (suggested_pipeline_id) REFERENCES pipelines(id) ON DELETE SET NULL
);",
            @"CREATE INDEX idx_objectives_tenant_status_updated ON objectives(tenant_id, status, last_update_utc DESC);",
            @"CREATE INDEX idx_objectives_tenant_backlog_priority_rank ON objectives(tenant_id, backlog_state, priority, rank);",
            @"CREATE INDEX idx_objectives_tenant_kind_priority ON objectives(tenant_id, kind, priority);",
            @"CREATE INDEX idx_objectives_tenant_owner ON objectives(tenant_id, owner);",
            @"CREATE INDEX idx_objectives_tenant_due ON objectives(tenant_id, due_utc);",
            @"CREATE INDEX idx_objectives_tenant_target_version ON objectives(tenant_id, target_version);",
            @"CREATE INDEX idx_objectives_tenant_parent ON objectives(tenant_id, parent_objective_id);",
            @"CREATE INDEX idx_objectives_tenant_source ON objectives(tenant_id, source_provider, source_type, source_id);",
            @"CREATE TABLE objective_refinement_sessions (
    id TEXT PRIMARY KEY,
    objective_id TEXT NOT NULL,
    tenant_id TEXT,
    user_id TEXT,
    captain_id TEXT NOT NULL,
    fleet_id TEXT,
    vessel_id TEXT,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Created',
    process_id INTEGER,
    failure_reason TEXT,
    created_utc TIMESTAMP NOT NULL,
    started_utc TIMESTAMP,
    completed_utc TIMESTAMP,
    last_update_utc TIMESTAMP NOT NULL,
    FOREIGN KEY (objective_id) REFERENCES objectives(id) ON DELETE CASCADE,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (captain_id) REFERENCES captains(id) ON DELETE NO ACTION,
    FOREIGN KEY (fleet_id) REFERENCES fleets(id) ON DELETE SET NULL,
    FOREIGN KEY (vessel_id) REFERENCES vessels(id) ON DELETE SET NULL
);",
            @"CREATE INDEX idx_objective_refinement_sessions_tenant_objective_created
    ON objective_refinement_sessions(tenant_id, objective_id, created_utc DESC);",
            @"CREATE INDEX idx_objective_refinement_sessions_tenant_captain_status
    ON objective_refinement_sessions(tenant_id, captain_id, status);",
            @"CREATE TABLE objective_refinement_messages (
    id TEXT PRIMARY KEY,
    objective_refinement_session_id TEXT NOT NULL,
    objective_id TEXT NOT NULL,
    tenant_id TEXT,
    user_id TEXT,
    role TEXT NOT NULL,
    sequence INTEGER NOT NULL,
    content TEXT NOT NULL,
    is_selected BOOLEAN NOT NULL DEFAULT FALSE,
    created_utc TIMESTAMP NOT NULL,
    last_update_utc TIMESTAMP NOT NULL,
    FOREIGN KEY (objective_refinement_session_id) REFERENCES objective_refinement_sessions(id) ON DELETE CASCADE,
    FOREIGN KEY (objective_id) REFERENCES objectives(id) ON DELETE CASCADE,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);",
            @"CREATE INDEX idx_objective_refinement_messages_session_sequence
    ON objective_refinement_messages(objective_refinement_session_id, sequence);",
            @"CREATE INDEX idx_objective_refinement_messages_objective_created
    ON objective_refinement_messages(objective_id, created_utc DESC);",
        };
    }
}
