namespace Armada.Test.Unit
{
    using Armada.Test.Common;
    using Armada.Test.Unit.Suites.Context;
    using Armada.Test.Unit.Suites.Database;
    using Armada.Test.Unit.Suites.Models;
    using Armada.Test.Unit.Suites.Recovery;
    using Armada.Test.Unit.Suites.Routes;
    using Armada.Test.Unit.Suites.Services;
    using Armada.Test.Unit.Suites.Settings;

    public class Program
    {
        public static async Task<int> Main(string[] args)
        {
            // Must run before anything touches Armada.Core.Constants: settings built without an
            // explicit DataDirectory otherwise resolve under the live Armada home and write there.
            TestDataDirectory.Redirect();
            TestDataDirectory.Verify();
            // Test repositories are short-lived, so git auto maintenance after commits is start-up cost only.
            global::Test.Shared.Infrastructure.TestGitEnvironment.DisableAutoMaintenance();

            TestHostOptions options;
            try
            {
                options = SuiteCommandLineOptions.ParseHost(args);
            }
            catch (ArgumentException ex)
            {
                Console.Error.WriteLine(ex.Message);
                return 1;
            }

            // A listing runs no test, and its output must be suite names only.
            if (!options.ListSuites)
                global::Test.Shared.Infrastructure.TestProcessEnvironment.RemoveProviderVariablesAndReport();

            TestRunner runner = new TestRunner("ARMADA UNIT TEST SUITE");

            runner.AddSuite(new TestRunnerContractTests());
            runner.AddSuite(new RuntimeLogFormatterTests());
            runner.AddSuite(new CaptainChatServiceTests());
            runner.AddSuite(new CaptainToolServiceDiscoveryTests());
            runner.AddSuite(new TelemetryLogExportTests());
            runner.AddSuite(new ContextIndexGeneratorTests());
            runner.AddSuite(new TypedDecisionRetentionTests());
            runner.AddSuite(new TypedDecisionWiringTests());
            runner.AddSuite(new ContextRetrievalServiceTests());
            runner.AddSuite(new ContextCoverageCensusTests());
            runner.AddSuite(new ContextBriefWiringTests());
            runner.AddSuite(new EmbeddingClientFactorySelectionTests());

            // Previously compiled suites are explicit registrations until discovery parity is proved.
            runner.AddSuite(new RequestHistoryDatabaseTests());
            runner.AddSuite(new ObjectiveModelTests());
            runner.AddSuite(new ObjectiveRefinementModelTests());
            runner.AddSuite(new DeploymentEnvironmentServiceTests());
            runner.AddSuite(new DeploymentServiceTests());
            runner.AddSuite(new HistoricalTimelineServiceTests());
            runner.AddSuite(new ProxyAuthServiceTests());
            runner.AddSuite(new ProxyDashboardRelayIntegrationTests());
            runner.AddSuite(new ProxyRoutePolicyServiceTests());
            runner.AddSuite(new RemoteDashboardRelayServiceTests());
            runner.AddSuite(new DashboardStaticFileTests());
            runner.AddSuite(new RequestHistoryCaptureServiceTests());
            runner.AddSuite(new ReviewGateTests());

            // Database tests
            runner.AddSuite(new FleetDatabaseTests());
            runner.AddSuite(new DefinitionOfDoneFailureClassifierTests());
            runner.AddSuite(new FailedTestNameExtractorTests());
            runner.AddSuite(new VesselDatabaseTests());
            runner.AddSuite(new VesselTests());
            runner.AddSuite(new CaptainDatabaseTests());
            runner.AddSuite(new CaptainTests());
            runner.AddSuite(new MissionDatabaseTests());
            runner.AddSuite(new MissionAssignmentStatePersistenceTests());
            runner.AddSuite(new VoyageDatabaseTests());
            runner.AddSuite(new DockDatabaseTests());
            runner.AddSuite(new SignalDatabaseTests());
            runner.AddSuite(new EventDatabaseTests());
            runner.AddSuite(new EventTests());
            runner.AddSuite(new EnumerationTests());
            runner.AddSuite(new ForeignKeyTests());
            runner.AddSuite(new ConcurrentAccessTests());
            runner.AddSuite(new DatabaseInitializationTests());
            runner.AddSuite(new PlanningSessionDatabaseTests());
            runner.AddSuite(new SchemaMigrationTests());
            runner.AddSuite(new PostgresBooleanColumnTypeTests());
            runner.AddSuite(new McpEnumerateChecksProjectionTests());
            runner.AddSuite(new VesselArchitectCapColumnTests());
            runner.AddSuite(new SchemaMigrationV42PipelineStageParallelTests());
            runner.AddSuite(new CapabilityHintSchemaTests());
            runner.AddSuite(new ObjectiveTenantNormalizationTests());
            runner.AddSuite(new ObjectiveAutoDispatchTests());
            runner.AddSuite(new SchemaMigrationV38RoundTripTests());
            runner.AddSuite(new EdgeCaseTests());
            runner.AddSuite(new TenantMethodsTests());
            runner.AddSuite(new UserMethodsTests());
            runner.AddSuite(new CredentialMethodsTests());
            runner.AddSuite(new TenantFencingTests());
            runner.AddSuite(new EntityTenantScopedTests());
            runner.AddSuite(new DefaultSeedingTests());
            runner.AddSuite(new TenantScopedEnumerationTests());
            runner.AddSuite(new TenantScopedPaginationTests());
            runner.AddSuite(new TenantScopedPaginationTests2());
            runner.AddSuite(new TransactionSupportTests());

            // Model tests
            runner.AddSuite(new FleetModelTests());
            runner.AddSuite(new VesselModelTests());
            runner.AddSuite(new CaptainModelTests());
            runner.AddSuite(new MissionModelTests());
            runner.AddSuite(new VoyageModelTests());
            runner.AddSuite(new PlanningSessionModelTests());
            runner.AddSuite(new DockModelTests());
            runner.AddSuite(new SignalModelTests());
            runner.AddSuite(new ArmadaEventModelTests());
            runner.AddSuite(new ArmadaStatusModelTests());
            runner.AddSuite(new EnumModelTests());
            runner.AddSuite(new TenantMetadataTests());
            runner.AddSuite(new UserMasterTests());
            runner.AddSuite(new CredentialTests());
            runner.AddSuite(new AuthContextTests());

            // Service tests
            runner.AddSuite(new AdmiralServiceTests());
            runner.AddSuite(new CaptainCrashLoopTrackerTests());
            runner.AddSuite(new MemoryHotfixRegressionTests());
            runner.AddSuite(new EntityResolverTests());
            runner.AddSuite(new MessageTemplateServiceTests());
            runner.AddSuite(new ProgressParserTests());
            runner.AddSuite(new PapercutTests());
            runner.AddSuite(new SettingsTests());
            runner.AddSuite(new UsageRoutingTests());
            runner.AddSuite(new SmartRoutingTests());
            runner.AddSuite(new TierRoutingCharacterizationTests());
            runner.AddSuite(new TierRecordMigrationTests());
            runner.AddSuite(new CaptainAccountLaunchTests());
            runner.AddSuite(new AccountLoginServiceTests());
            runner.AddSuite(new ReleaseVersionTests());
            runner.AddSuite(new ReleaseServiceTests());
            runner.AddSuite(new StartupScriptTests());
            runner.AddSuite(new GitServiceTests());
            runner.AddSuite(new GitServiceIsPrMergedTests());
            runner.AddSuite(new GitServiceCommitCountTests());
            runner.AddSuite(new ManualCompletionProofServiceTests());
            runner.AddSuite(new GitInferenceTests());
            runner.AddSuite(new DockServiceTests());
            runner.AddSuite(new DockPathOccupantsTests());
            runner.AddSuite(new LogRotationServiceTests());
            runner.AddSuite(new DataExpiryServiceTests());
            runner.AddSuite(new NotificationServiceTests());
            runner.AddSuite(new RuntimeDetectionServiceTests());
            runner.AddSuite(new RuntimeOutputFormattingTests());
            runner.AddSuite(new RemoteTunnelManagerTests());
            runner.AddSuite(new ProxyRegistryTests());
            runner.AddSuite(new RemoteControlQueryServiceTests());
            runner.AddSuite(new RemoteControlManagementServiceTests());
            runner.AddSuite(new WebSocketClientOutputQueueTests());
            runner.AddSuite(new WebSocketReplayBufferTests());
            runner.AddSuite(new FleetReconciliationSnapshotServiceTests());
            runner.AddSuite(new CaptainServiceTests());
            runner.AddSuite(new AgentLifecycleHandlerTests());
            runner.AddSuite(new PlanningSessionCoordinatorTests());
            runner.AddSuite(new MissionPromptTests());
            runner.AddSuite(new MissionSubjectExtractorTests());
            runner.AddSuite(new MissionHandoffIdempotencyTests());
            runner.AddSuite(new MissionHandoffBranchAdvanceTests());
            runner.AddSuite(new MissionModeTests());
            runner.AddSuite(new VesselLaneMapTests());
            runner.AddSuite(new SiblingLaneAdmissionTests());
            runner.AddSuite(new FleetCapacityAdmissionTests());
            runner.AddSuite(new TestOwnershipResolverTests());
            runner.AddSuite(new SequentialDispatchTests());
            runner.AddSuite(new MissionStatusTransitionTests());
            runner.AddSuite(new CaptainPersonaMatchingTests());
            runner.AddSuite(new ProjectProfileBriefInjectionTests());
            runner.AddSuite(new CaptainOverridePersistenceTests());
            runner.AddSuite(new CaptainProcessLivenessTests());
            runner.AddSuite(new MissionTransitionTableAgreementTests());
            runner.AddSuite(new StageBranchInheritanceTests());
            runner.AddSuite(new LandingPipelineTests());
            runner.AddSuite(new LandingServiceTests());
            runner.AddSuite(new LandingStateMachineTests());
            runner.AddSuite(new SessionTokenServiceTests());
            runner.AddSuite(new AuthenticationServiceTests());
            runner.AddSuite(new AuthorizationConfigTests());
            runner.AddSuite(new AuthorizationServiceTests());
            runner.AddSuite(new AuthEndpointTests());
            runner.AddSuite(new PromptTemplateServiceTests());
            runner.AddSuite(new PromptSignalConsistencyTests());
            runner.AddSuite(new PersonaSeedServiceTests());
            runner.AddSuite(new PersonaPipelineDbTests());
            runner.AddSuite(new PipelineDispatchTests());
            runner.AddSuite(new DispatchAssignmentStateTests());
            runner.AddSuite(new PerStagePreferredModelTests());
            runner.AddSuite(new AliasPipelineDispatchTests());
            runner.AddSuite(new CrossVesselDependencyTests());
            runner.AddSuite(new CancelKillsCaptainTests());
            runner.AddSuite(new PrFallbackPersistenceTests());
            runner.AddSuite(new PrFallbackUnblockTests());
            runner.AddSuite(new JudgeHybridFollowUpsTests());
            runner.AddSuite(new JudgeFollowUpPersistenceTests());
            runner.AddSuite(new JudgeVerdictRobustnessTests());
            runner.AddSuite(new JudgeAcceptanceWalkTests());
            runner.AddSuite(new DependsOnMissionIdDispatchTests());
            runner.AddSuite(new AutoLandEvaluatorTests());
            runner.AddSuite(new OpenCodePermissionConfigBuilderTests());
            runner.AddSuite(new CodexProviderRoutingTests());
            runner.AddSuite(new CursorLaunchArgumentsTests());
            runner.AddSuite(new OpenCodeProviderConfigBuilderTests());
            runner.AddSuite(new ClaudeCodeProviderRoutingTests());
            runner.AddSuite(new ResourcePressureAdmissionTests());
            runner.AddSuite(new DatabaseValidationModeTests());
            runner.AddSuite(new CaptainQuarantineTests());
            runner.AddSuite(new ProviderQuotaLimitDetectorTests());
            runner.AddSuite(new MissionFailureCreditQuarantineTests());
            runner.AddSuite(new MissionSafeguardRerouteTests());
            runner.AddSuite(new MissionCompletionRequeueTests());
            runner.AddSuite(new MissionCompletionAttemptTests());
            runner.AddSuite(new CaptainStallDecisionTests());
            runner.AddSuite(new CaptainRefusalClassifierTests());
            runner.AddSuite(new PolicyRefusalContinuationServiceTests());
            runner.AddSuite(new MissionQuotaRerouteTests());
            runner.AddSuite(new MissionReviewDiffTests());
            runner.AddSuite(new CaptainBenchPersistenceTests());
            runner.AddSuite(new McpVesselToolsTests());
            runner.AddSuite(new McpCreateOwnershipTests());
            runner.AddSuite(new WebSocketCreateOwnershipTests());
            runner.AddSuite(new WebSocketMissionSummaryTests());
            runner.AddSuite(new WebSocketCommandAuthorizationTests());
            runner.AddSuite(new WebSocketCommandRegistryTests());
            runner.AddSuite(new AutonomousObjectiveSelectorTests());
            runner.AddSuite(new ObjectiveFairShareOrderTests());
            runner.AddSuite(new ConventionCheckTests());
            runner.AddSuite(new DockBoundaryScannerTests());
            runner.AddSuite(new DockBoundaryManifestHashTests());
            runner.AddSuite(new DockBoundaryManifestHashEdgeTests());
            runner.AddSuite(new DockBoundaryBase64ChunkEntropyTests());
            runner.AddSuite(new DockBoundaryConfigTests());
            runner.AddSuite(new ConventionCheckerSecretPatternsTests());
            runner.AddSuite(new CriticalTriggerEvaluatorTests());
            runner.AddSuite(new DeterministicLogScreenPassTests());
            runner.AddSuite(new CaptainLogScreenServiceTests());
            runner.AddSuite(new LogWatchScreenPassTests());
            runner.AddSuite(new CaptainLogScreeningSettingsTests());
            runner.AddSuite(new AutoLandLandingHandlerTests());
            runner.AddSuite(new WorkerNoOpFailureGuardTests());
            runner.AddSuite(new ProcessExitFailureReasonTests());
            runner.AddSuite(new PlaybookContentGateTests());
            runner.AddSuite(new PersonaBranchAttachmentTests());
            runner.AddSuite(new CodeRetrievalGoalTests());
            runner.AddSuite(new ParallelStageBarrierTests());
            runner.AddSuite(new JudgeChecksGateTests());
            runner.AddSuite(new VoyageReportOnlyClassifierTests());
            runner.AddSuite(new StaleCheckSupersessionTests());
            runner.AddSuite(new Suites.Services.WorkspaceServiceTests());
            runner.AddSuite(new Suites.Services.InboxServiceTests());
            runner.AddSuite(new Suites.Services.LongRunningJobServiceTests());
            runner.AddSuite(new Suites.Services.ArmadaServerStopTests());
            runner.AddSuite(new Suites.Services.CodeIndexStalenessTests());
            runner.AddSuite(new Suites.Services.BranchCleanupSweepTests());
            runner.AddSuite(new Suites.Services.HealthLoopMaintenanceRunnerTests());
            runner.AddSuite(new JudgePromptLensTests());
            runner.AddSuite(new AutoLandSafetyNetIntegrationTests());
            runner.AddSuite(new AutoLandCalibrationTests());
            runner.AddSuite(new PrestagedFilesTests());
            runner.AddSuite(new ReadContextStagerTests());
            runner.AddSuite(new ProtectedPathsTests());
            runner.AddSuite(new VesselAutoLandPredicateRoutesTests());
            runner.AddSuite(new CaptainUpdateValidationTests());
            runner.AddSuite(new CaptainServerOwnedFieldTests());
            runner.AddSuite(new CaptainAdministrationTests());
            runner.AddSuite(new TierRoutingWriteSurfaceTests());
            runner.AddSuite(new ApiEndpointPersonaAdmissionTests());
            runner.AddSuite(new VesselDefaultPlaybooksTests());
            runner.AddSuite(new VesselModelContextBoundaryTests());
            runner.AddSuite(new VesselSiblingReposRoutesTests());
            runner.AddSuite(new CodeIndexRoutesTests());
            runner.AddSuite(new ServerRestartRouteTests());
            runner.AddSuite(new AuditDrainerTests());
            runner.AddSuite(new ArmedCheckEligibilityTests());
            runner.AddSuite(new LandingStatusTruthTests());
            runner.AddSuite(new DependencyChainCancellationTests());
            runner.AddSuite(new WorkflowProfileEnvironmentTests());
            runner.AddSuite(new ArchitectOutputParserTests());
            runner.AddSuite(new McpArchitectToolsTests());
            runner.AddSuite(new ArchitectPersonaSyncTests());
            runner.AddSuite(new RemoteTriggerSettingsTests());
            runner.AddSuite(new RemoteTriggerHttpClientTests());
            runner.AddSuite(new RemoteTriggerServiceTests());
            runner.AddSuite(new CdWebhookSettingsTests());
            runner.AddSuite(new ReleaseWebhookDispatcherTests());
            runner.AddSuite(new RemoteTriggerEventHookTests());
            runner.AddSuite(new IncidentServiceTests());
            runner.AddSuite(new ObjectiveServiceTests());
            runner.AddSuite(new KeyedAsyncLockTests());
            runner.AddSuite(new ObjectiveTerminalBacklogStateTests());
            runner.AddSuite(new ObjectiveDispatchAttemptTests());
            runner.AddSuite(new ObjectiveRefinementCoordinatorTests());
            runner.AddSuite(new ObjectiveDependencyAnalyzerTests());
            runner.AddSuite(new ObjectiveBriefRendererTests());
            runner.AddSuite(new AutonomousRecoveryOrchestratorTests());
            runner.AddSuite(new LandingDrainSafetyNetTests());
            runner.AddSuite(new AutonomousObjectiveSchedulerTests());
            runner.AddSuite(new IncidentLifecycleOrchestratorTests());
            runner.AddSuite(new MergeQueueBranchCleanupTests());
            runner.AddSuite(new MergeQueueServiceTests());
            runner.AddSuite(new MergeQueueServiceClassificationTests());
            runner.AddSuite(new MergeFailureClassifierTests());
            runner.AddSuite(new ProviderStallClassifierTests());
            runner.AddSuite(new RebaseCaptainDockSetupTests());
            runner.AddSuite(new MergeRecoveryHandlerRebasePathTests());
            runner.AddSuite(new RecoveryExhaustionFlowTests());
            runner.AddSuite(new AutoRecoveryEndToEndSmokeTests());
            runner.AddSuite(new RescueVoyageHandoffTests());
            runner.AddSuite(new PlaybookMergeTests());
            runner.AddSuite(new PullRequestServiceTests());
            runner.AddSuite(new VoyageMissionPlaybookPropagationTests());
            runner.AddSuite(new MissionAliasResolverTests());
            runner.AddSuite(new CSharpSymbolExtractorTests());
            runner.AddSuite(new CSharpSymbolExtractorNegativePathTests());
            runner.AddSuite(new PolyglotSymbolExtractorTests());
            runner.AddSuite(new CodeIndexServiceTests());
            runner.AddSuite(new CodeIndexFastPackTests());
            runner.AddSuite(new CodeIndexServiceGraphSidecarTests());
            runner.AddSuite(new CodeIndexServiceGraphQueryTests());
            runner.AddSuite(new CodeIndexServiceGraphQueryNegativePathTests());
            runner.AddSuite(new CodeIndexServiceSignatureTests());
            runner.AddSuite(new CodeIndexServiceSummarizerTests());
            runner.AddSuite(new CodeIndexServiceSummarizerNegativePathTests());
            runner.AddSuite(new FleetCodeIndexServiceTests());
            runner.AddSuite(new CodeIndexSettingsClampTests());
            runner.AddSuite(new CodeContextTimeoutsTests());
            runner.AddSuite(new VoyageEmbeddingClientTests());
            runner.AddSuite(new DeepSeekInferenceClientTests());
            runner.AddSuite(new TypeSafeDecisionClientTests());
            runner.AddSuite(new DecisionStateRedactorTests());
            runner.AddSuite(new TypedDecisionRecorderTests());
            runner.AddSuite(new TypedDecisionBatcherTests());
            runner.AddSuite(new TypedDecisionEvalTests());
            runner.AddSuite(new TypedDecisionSettingsTests());
            runner.AddSuite(new CustomTypedDecisionTests());
            runner.AddSuite(new CustomDecisionHandoffTests());
            runner.AddSuite(new BannedDiffPatternTests());
            runner.AddSuite(new TypedDecisionKeyTests());
            runner.AddSuite(new McpTypedDecisionToolsTests());
            runner.AddSuite(new McpContextToolsTests());
            runner.AddSuite(new TypedDecisionGateMatrixTests());
            runner.AddSuite(new BuiltinDecisionDefinitionTests());
            runner.AddSuite(new TypedFailureCauseAdapterTests());
            runner.AddSuite(new TypedRefusalAdapterTests());
            runner.AddSuite(new TypedRuntimeFailureAdapterTests());
            runner.AddSuite(new TypedReviewSubstanceAdapterTests());
            runner.AddSuite(new TypedStageNecessityAdapterTests());
            runner.AddSuite(new TypedHandoffOutcomeAdapterTests());
            runner.AddSuite(new TypedOwnerDigestAdapterTests());
            runner.AddSuite(new PapercutMergeAdapterTests());
            runner.AddSuite(new MemoryCandidateAdapterTests());
            runner.AddSuite(new PreflightTextAdapterTests());
            runner.AddSuite(new TypedFlakeScoreAdapterTests());
            runner.AddSuite(new TypedChangeSubstanceAdapterTests());
            runner.AddSuite(new CriteriaLintAdapterTests());
            runner.AddSuite(new InboxTriageAdapterTests());
            runner.AddSuite(new FollowUpRoutingAdapterTests());
            runner.AddSuite(new TypedRevisionKindAdapterTests());
            runner.AddSuite(new TypedTestCoversAdapterTests());
            runner.AddSuite(new ToolOutputRetentionTests());
            runner.AddSuite(new TypedDecisionEgressRuleTests());
            runner.AddSuite(new TypedLintFindingAdapterTests());
            runner.AddSuite(new LeakHunkAdapterTests());
            runner.AddSuite(new PriorArtRetrieverTests());
            runner.AddSuite(new GitPriorArtSourceTests());
            runner.AddSuite(new TypedPriorArtAdapterTests());
            runner.AddSuite(new MemoryProposalTests());
            runner.AddSuite(new OpenCodeServerInferenceClientTests());
            runner.AddSuite(new OpenCodeServerInferenceClientNegativePathTests());
            runner.AddSuite(new OpenCodeServerLauncherTests());
            runner.AddSuite(new OpenCodeServerLauncherNegativePathTests());
            runner.AddSuite(new CodeIndexProductionWiringTests());
            runner.AddSuite(new CodeIndexRefreshSchedulerTests());
            runner.AddSuite(new McpCodeIndexToolsTests());
            runner.AddSuite(new StructuralChunkerTests());
            runner.AddSuite(new CodeDuplicateFinderTests());
            runner.AddSuite(new ChangeQualityRulesTests());
            runner.AddSuite(new TypedChangeQualityAdapterTests());
            runner.AddSuite(new TypedDispatchStalenessAdapterTests());
            runner.AddSuite(new ChangeQualityGateTests());
            runner.AddSuite(new McpChangeQualityToolsTests());
            runner.AddSuite(new McpCheckRunToolsTests());
            runner.AddSuite(new WorkflowProfileCheckRunServiceTests());
            runner.AddSuite(new CheckRunIsolatedCheckoutTests());
            runner.AddSuite(new SiblingLeaseRegistryTests());
            runner.AddSuite(new ConsumerVesselResolverTests());
            runner.AddSuite(new VoyageCheckArmingPlanTests());
            runner.AddSuite(new SlopDiffClassifierTests());
            runner.AddSuite(new SlopCheckExecutionTests());
            runner.AddSuite(new CheckRunSummaryViewTests());
            runner.AddSuite(new RescueEffectivenessTests());
            runner.AddSuite(new StalePauseRuleTests());
            runner.AddSuite(new StageBaseVerifierTests());
            runner.AddSuite(new DiskLifecycleTests());
            runner.AddSuite(new CheckRunParsingServiceTests());
            runner.AddSuite(new MergeRefCandidateTests());
            runner.AddSuite(new TestDataDirectoryIsolationTests());
            runner.AddSuite(new MergeFailureClassifierGitOutputTests());
            runner.AddSuite(new McpCaptainDiagnosticsToolsTests());
            runner.AddSuite(new McpStdioServerTests());
            runner.AddSuite(new ArmadaMcpHttpServerTests());
            runner.AddSuite(new VoyageDispatchServiceTests());
            runner.AddSuite(new ContextPackStagingHardFailTests());
            runner.AddSuite(new McpVoyageToolsTests());
            runner.AddSuite(new VoyageStatusAssignmentSurfaceTests());
            runner.AddSuite(new McpMissionToolsTests());
            runner.AddSuite(new MissionOutputArtifactTests());
            runner.AddSuite(new PromptBudgetSummaryTests());
            runner.AddSuite(new PreferredModelTierSelectorTests());
            runner.AddSuite(new CapabilityRoutingTests());
            runner.AddSuite(new CapabilityRoutingSelectionTests());
            runner.AddSuite(new PreferredModelUserGuidanceTests());
            runner.AddSuite(new MissionServicePreferredModelRoutingTests());
            runner.AddSuite(new MissionServiceRequestedCaptainRoutingTests());
            runner.AddSuite(new MissionServiceNoOpCompletionTests());
            runner.AddSuite(new MissionServiceSelfHealHandoffTests());
            runner.AddSuite(new MissionServiceTerminalBranchReapTests());
            runner.AddSuite(new TerminalVoyageMissionReconcilerTests());
            runner.AddSuite(new SchedulerHydrationTests());
            runner.AddSuite(new SchedulerCapacityTests());
            runner.AddSuite(new VoyageMailboxSignalPayloadTests());
            runner.AddSuite(new McpSignalToolsTests());
            runner.AddSuite(new McpToolArgumentNormalizerTests());
            runner.AddSuite(new QueryValueReaderTests());
            runner.AddSuite(new PostgresqlUtcReadTests());
            runner.AddSuite(new MissionMailboxDrainTests());
            runner.AddSuite(new BuildDriftEvaluatorTests());
            runner.AddSuite(new BuildDriftServiceTests());
            runner.AddSuite(new SelfDeployServiceTests());
            runner.AddSuite(new DatabaseBackupServiceTests());
            runner.AddSuite(new SelfDeployNativeClientTests());
            runner.AddSuite(new SelfDeployPrivateStorageBackendTests());
            runner.AddSuite(new SelfDeployDatabaseBackupProviderTests());
            runner.AddSuite(new SelfDeployBuildRunnerTests());
            runner.AddSuite(new SelfDeployNativeIntegrationTests());
            runner.AddSuite(new SelfDeployCutoverCoordinatorTests());
            runner.AddSuite(new SelfDeployRestartRecordStoreTests());
            runner.AddSuite(new SelfDeployArtifactStoreTests());
            runner.AddSuite(new SelfDeployHttpHealthProbeTests());
            runner.AddSuite(new HarborRunnerSessionRegistryTests());
            runner.AddSuite(new HarborRunnerEnrollmentServiceTests());
            runner.AddSuite(new HarborProtocolTests());
            runner.AddSuite(new HarborTransportTests());
            runner.AddSuite(new AutonomousObjectiveSchedulerSettingsTests());
            runner.AddSuite(new ArchitectSettingsTests());
            runner.AddSuite(new VesselLocalPathAndLagunaTierTests());
            runner.AddSuite(new DispatchFailFastTests());
            runner.AddSuite(new DispatchCodeContextBoundedTests());
            runner.AddSuite(new McpObjectiveSchedulerToolsTests());
            runner.AddSuite(new VerifiedProductionSummaryServiceTests());
            runner.AddSuite(new MissionAttemptFactRecorderTests());
            runner.AddSuite(new PreparationClaimObservationRecorderTests());
            runner.AddSuite(new LaneStateRecorderTests());
            runner.AddSuite(new McpProductionToolsTests());
            runner.AddSuite(new McpResultPreviewTests());
            runner.AddSuite(new DefinitionOfDoneGateTests());
            runner.AddSuite(new DefinitionOfDoneReportTests());
            runner.AddSuite(new MissionRecoveryReportTests());
            runner.AddSuite(new CaptainQuarantineScopedServiceTests());
            runner.AddSuite(new MissionAutoLandReportTests());
            runner.AddSuite(new EventOwnerScopeTests());
            runner.AddSuite(new DockBoundaryHookExecutionTests());
            runner.AddSuite(new DockBoundaryHookCoverageTests());
            runner.AddSuite(new UnlandedBranchServiceTests());
            runner.AddSuite(new VesselBranchWriteServiceTests());
            runner.AddSuite(new CoordinationDatabaseTests());
            runner.AddSuite(new CoordinationServiceTests());
            runner.AddSuite(new CoordinationClaimTests());
            runner.AddSuite(new CoordinationCaptainVoiceTests());
            runner.AddSuite(new DispatchHoldTests());
            runner.AddSuite(new SchedulerMissionModeTests());
            runner.AddSuite(new DispatchObjectiveModeTests());
            runner.AddSuite(new ObjectiveDispatchPreviewServiceTests());
            runner.AddSuite(new ObjectivePreflightGateTests());
            runner.AddSuite(new MemoryDatabaseTests());
            runner.AddSuite(new MemoryServiceTests());
            runner.AddSuite(new McpMemoryToolsTests());
            runner.AddSuite(new OwnershipScopeTests());
            runner.AddSuite(new WebSocketDeliveryScopeTests());
            runner.AddSuite(new CaptainRuntimeToolCatalogHttpProbeTests());
            runner.AddSuite(new McpEnumArgumentFailureTests());
            runner.AddSuite(new MissionUnassignableEscalationTests());

            runner.VerifyRegistration(typeof(Program).Assembly);

            // The weight table and serial list are loaded for every run, so a stale serial entry fails a
            // plain run as well as a sharded one instead of silently unpinning a suite.
            SuiteShardPlan plan;
            try
            {
                plan = SuiteShardPlan.Load(
                    Path.Combine(AppContext.BaseDirectory, "shard-weights.json"),
                    Path.Combine(AppContext.BaseDirectory, "serial-suites.json"));
                plan.Assign(runner.GetSuiteNames(), 1);
            }
            catch (Exception ex) when (ex is IOException || ex is InvalidOperationException || ex is System.Text.Json.JsonException)
            {
                Console.Error.WriteLine("Invalid shard plan: " + ex.Message);
                return 1;
            }

            if (options.ListSuites) return runner.ListSuites(options.Shard, plan);

            int exitCode = await runner.RunAllAsync(options.SuiteFilters, options.Shard, plan).ConfigureAwait(false);
            return exitCode;
        }
    }
}
