namespace Armada.Test.Unit
{
    using Armada.Test.Common;
    using Armada.Test.Unit.Suites.Database;
    using Armada.Test.Unit.Suites.Models;
    using Armada.Test.Unit.Suites.Recovery;
    using Armada.Test.Unit.Suites.Routes;
    using Armada.Test.Unit.Suites.Services;
    using Armada.Test.Unit.Suites.Settings;

    public class Program
    {
        public static async Task<int> Main(string[] args)
        {
            bool noCleanup = args.Contains("--no-cleanup");
            List<string> suiteFilters = new List<string>();
            for (int i = 0; i < args.Length; i++)
            {
                if (!String.Equals(args[i], "--suite", StringComparison.OrdinalIgnoreCase)) continue;
                if (i + 1 < args.Length) suiteFilters.Add(args[++i]);
            }

            TestRunner runner = new TestRunner("ARMADA UNIT TEST SUITE");

            // Database tests
            runner.AddSuite(new FleetDatabaseTests());
            runner.AddSuite(new VesselDatabaseTests());
            runner.AddSuite(new VesselTests());
            runner.AddSuite(new CaptainDatabaseTests());
            runner.AddSuite(new CaptainTests());
            runner.AddSuite(new MissionDatabaseTests());
            runner.AddSuite(new MissionAssignmentStatePersistenceTests());
            runner.AddSuite(new VoyageDatabaseTests());
            runner.AddSuite(new DockDatabaseTests());
            runner.AddSuite(new SignalDatabaseTests());
            runner.AddSuite(new EventDatabaseTests());
            runner.AddSuite(new EventTests());
            runner.AddSuite(new EnumerationTests());
            runner.AddSuite(new ForeignKeyTests());
            runner.AddSuite(new ConcurrentAccessTests());
            runner.AddSuite(new DatabaseInitializationTests());
            runner.AddSuite(new PlanningSessionDatabaseTests());
            runner.AddSuite(new SchemaMigrationTests());
            runner.AddSuite(new SchemaMigrationV40ReflectionTests());
            runner.AddSuite(new SchemaMigrationV41ReorganizeTests());
            runner.AddSuite(new VesselArchitectCapColumnTests());
            runner.AddSuite(new SchemaMigrationV42PipelineStageParallelTests());
            runner.AddSuite(new ObjectiveTenantNormalizationTests());
            runner.AddSuite(new ObjectiveAutoDispatchTests());
            runner.AddSuite(new SchemaMigrationV38RoundTripTests());
            runner.AddSuite(new EdgeCaseTests());
            runner.AddSuite(new TenantMethodsTests());
            runner.AddSuite(new UserMethodsTests());
            runner.AddSuite(new CredentialMethodsTests());
            runner.AddSuite(new TenantFencingTests());
            runner.AddSuite(new EntityTenantScopedTests());
            runner.AddSuite(new DefaultSeedingTests());
            runner.AddSuite(new TenantScopedEnumerationTests());
            runner.AddSuite(new TenantScopedPaginationTests());
            runner.AddSuite(new TenantScopedPaginationTests2());
            runner.AddSuite(new TransactionSupportTests());

            // Model tests
            runner.AddSuite(new FleetModelTests());
            runner.AddSuite(new VesselModelTests());
            runner.AddSuite(new CaptainModelTests());
            runner.AddSuite(new MissionModelTests());
            runner.AddSuite(new VoyageModelTests());
            runner.AddSuite(new PlanningSessionModelTests());
            runner.AddSuite(new DockModelTests());
            runner.AddSuite(new SignalModelTests());
            runner.AddSuite(new ArmadaEventModelTests());
            runner.AddSuite(new ArmadaStatusModelTests());
            runner.AddSuite(new EnumModelTests());
            runner.AddSuite(new TenantMetadataTests());
            runner.AddSuite(new UserMasterTests());
            runner.AddSuite(new CredentialTests());
            runner.AddSuite(new AuthContextTests());

            // Service tests
            runner.AddSuite(new AdmiralServiceTests());
            runner.AddSuite(new MemoryHotfixRegressionTests());
            runner.AddSuite(new EntityResolverTests());
            runner.AddSuite(new MessageTemplateServiceTests());
            runner.AddSuite(new ProgressParserTests());
            runner.AddSuite(new SettingsTests());
            runner.AddSuite(new ReleaseVersionTests());
            runner.AddSuite(new StartupScriptTests());
            runner.AddSuite(new GitServiceTests());
            runner.AddSuite(new GitServiceIsPrMergedTests());
            runner.AddSuite(new GitServiceCommitCountTests());
            runner.AddSuite(new GitInferenceTests());
            runner.AddSuite(new DockServiceTests());
            runner.AddSuite(new LogRotationServiceTests());
            runner.AddSuite(new DataExpiryServiceTests());
            runner.AddSuite(new NotificationServiceTests());
            runner.AddSuite(new RuntimeDetectionServiceTests());
            runner.AddSuite(new RemoteTunnelManagerTests());
            runner.AddSuite(new ProxyRegistryTests());
            runner.AddSuite(new RemoteControlQueryServiceTests());
            runner.AddSuite(new RemoteControlManagementServiceTests());
            runner.AddSuite(new CaptainServiceTests());
            runner.AddSuite(new AgentLifecycleHandlerTests());
            runner.AddSuite(new PlanningSessionCoordinatorTests());
            runner.AddSuite(new MissionPromptTests());
            runner.AddSuite(new SequentialDispatchTests());
            runner.AddSuite(new MissionStatusTransitionTests());
            runner.AddSuite(new MissionWaitingForInputStatusTests());
            runner.AddSuite(new WaitingForInputLifecycleTests());
            runner.AddSuite(new LandingPipelineTests());
            runner.AddSuite(new LandingServiceTests());
            runner.AddSuite(new LandingStateMachineTests());
            runner.AddSuite(new SessionTokenServiceTests());
            runner.AddSuite(new AuthenticationServiceTests());
            runner.AddSuite(new AuthorizationConfigTests());
            runner.AddSuite(new AuthorizationServiceTests());
            runner.AddSuite(new AuthEndpointTests());
            runner.AddSuite(new PromptTemplateServiceTests());
            runner.AddSuite(new PromptSignalConsistencyTests());
            runner.AddSuite(new PersonaSeedServiceTests());
            runner.AddSuite(new PersonaPipelineDbTests());
            runner.AddSuite(new PipelineDispatchTests());
            runner.AddSuite(new DispatchAssignmentStateTests());
            runner.AddSuite(new PerStagePreferredModelTests());
            runner.AddSuite(new AliasPipelineDispatchTests());
            runner.AddSuite(new CrossVesselDependencyTests());
            runner.AddSuite(new CancelKillsCaptainTests());
            runner.AddSuite(new PrFallbackPersistenceTests());
            runner.AddSuite(new PrFallbackUnblockTests());
            runner.AddSuite(new JudgeHybridFollowUpsTests());
            runner.AddSuite(new DependsOnMissionIdDispatchTests());
            runner.AddSuite(new AutoLandEvaluatorTests());
            runner.AddSuite(new CaptainHealthMonitorTests());
            runner.AddSuite(new AutonomousObjectiveSelectorTests());
            runner.AddSuite(new ConventionCheckTests());
            runner.AddSuite(new CriticalTriggerEvaluatorTests());
            runner.AddSuite(new AutoLandLandingHandlerTests());
            runner.AddSuite(new AutoLandSafetyNetIntegrationTests());
            runner.AddSuite(new AutoLandCalibrationTests());
            runner.AddSuite(new PrestagedFilesTests());
            runner.AddSuite(new ProtectedPathsTests());
            runner.AddSuite(new VesselAutoLandPredicateRoutesTests());
            runner.AddSuite(new VesselDefaultPlaybooksTests());
            runner.AddSuite(new VesselSiblingReposRoutesTests());
            runner.AddSuite(new CodeIndexRoutesTests());
            runner.AddSuite(new AuditDrainerTests());
            runner.AddSuite(new ReflectionAuditDrainTests());
            runner.AddSuite(new ArchitectOutputParserTests());
            runner.AddSuite(new ReflectionOutputParserTests());
            runner.AddSuite(new McpArchitectToolsTests());
            runner.AddSuite(new ArchitectPersonaSyncTests());
            runner.AddSuite(new RemoteTriggerSettingsTests());
            runner.AddSuite(new RemoteTriggerHttpClientTests());
            runner.AddSuite(new RemoteTriggerServiceTests());
            runner.AddSuite(new RemoteTriggerEventHookTests());
            runner.AddSuite(new IncidentServiceTests());
            runner.AddSuite(new ObjectiveServiceTests());
            runner.AddSuite(new AutonomousRecoveryOrchestratorTests());
            runner.AddSuite(new AutonomousObjectiveSchedulerTests());
            runner.AddSuite(new IncidentLifecycleOrchestratorTests());
            runner.AddSuite(new MergeQueueBranchCleanupTests());
            runner.AddSuite(new MergeQueueServiceTests());
            runner.AddSuite(new MergeQueueServiceClassificationTests());
            runner.AddSuite(new MergeFailureClassifierTests());
            runner.AddSuite(new RebaseCaptainDockSetupTests());
            runner.AddSuite(new MergeRecoveryHandlerRebasePathTests());
            runner.AddSuite(new RecoveryExhaustionFlowTests());
            runner.AddSuite(new AutoRecoveryEndToEndSmokeTests());
            runner.AddSuite(new PlaybookMergeTests());
            runner.AddSuite(new PullRequestServiceTests());
            runner.AddSuite(new VoyageMissionPlaybookPropagationTests());
            runner.AddSuite(new MissionAliasResolverTests());
            runner.AddSuite(new CSharpSymbolExtractorTests());
            runner.AddSuite(new CSharpSymbolExtractorNegativePathTests());
            runner.AddSuite(new PolyglotSymbolExtractorTests());
            runner.AddSuite(new CodeIndexServiceTests());
            runner.AddSuite(new CodeIndexFastPackTests());
            runner.AddSuite(new CodeIndexServiceGraphSidecarTests());
            runner.AddSuite(new CodeIndexServiceGraphQueryTests());
            runner.AddSuite(new CodeIndexServiceGraphQueryNegativePathTests());
            runner.AddSuite(new CodeIndexServiceSignatureTests());
            runner.AddSuite(new CodeIndexServiceSummarizerTests());
            runner.AddSuite(new CodeIndexServiceSummarizerNegativePathTests());
            runner.AddSuite(new FleetCodeIndexServiceTests());
            runner.AddSuite(new CodeIndexSettingsClampTests());
            runner.AddSuite(new CodeContextTimeoutsTests());
            runner.AddSuite(new DeepSeekEmbeddingClientTests());
            runner.AddSuite(new DeepSeekInferenceClientTests());
            runner.AddSuite(new OpenCodeServerInferenceClientTests());
            runner.AddSuite(new OpenCodeServerInferenceClientNegativePathTests());
            runner.AddSuite(new OpenCodeServerLauncherTests());
            runner.AddSuite(new OpenCodeServerLauncherNegativePathTests());
            runner.AddSuite(new CodeIndexProductionWiringTests());
            runner.AddSuite(new McpCodeIndexToolsTests());
            runner.AddSuite(new McpCheckRunToolsTests());
            runner.AddSuite(new McpCaptainDiagnosticsToolsTests());
            runner.AddSuite(new McpStdioServerTests());
            runner.AddSuite(new McpVoyageToolsTests());
            runner.AddSuite(new VoyageStatusAssignmentSurfaceTests());
            runner.AddSuite(new McpMissionToolsTests());
            runner.AddSuite(new PreferredModelTierSelectorTests());
            runner.AddSuite(new PreferredModelUserGuidanceTests());
            runner.AddSuite(new MissionServicePreferredModelRoutingTests());
            runner.AddSuite(new SchedulerHydrationTests());
            runner.AddSuite(new ReflectionMemoryBootstrapServiceTests());
            runner.AddSuite(new ReflectionConsolidateToolsTests());
            runner.AddSuite(new ReflectionAcceptRejectToolsTests());
            runner.AddSuite(new ReflectionAnchorTests());
            runner.AddSuite(new StaleAnchorDetectorTests());
            runner.AddSuite(new StaleAnchorDetectorEdgeCaseTests());
            runner.AddSuite(new ReflectionsEndToEndSmokeTests());
            runner.AddSuite(new ReflectionsV2F4EndToEndSmokeTests());
            runner.AddSuite(new ReflectionsV2F1EndToEndSmokeTests());
            runner.AddSuite(new ReflectionsV2F2EndToEndSmokeTests());
            runner.AddSuite(new ReflectionsV2F3EndToEndSmokeTests());
            runner.AddSuite(new VesselReflectionThresholdRoutesTests());
            runner.AddSuite(new VesselReorganizeThresholdRoutesTests());
            runner.AddSuite(new VoyageMailboxSignalPayloadTests());
            runner.AddSuite(new McpSignalToolsTests());
            runner.AddSuite(new MissionMailboxDrainTests());
            runner.AddSuite(new BuildDriftEvaluatorTests());
            runner.AddSuite(new BuildDriftServiceTests());
            runner.AddSuite(new SelfDeployServiceTests());
            runner.AddSuite(new AutonomousObjectiveSchedulerSettingsTests());
            runner.AddSuite(new ArchitectSettingsTests());
            runner.AddSuite(new McpObjectiveSchedulerToolsTests());

            int exitCode = await runner.RunAllAsync(suiteFilters).ConfigureAwait(false);
            return exitCode;
        }
    }
}
