namespace Armada.Core.Models
{
    /// <summary>
    /// Per-file semantic signature record used for file-level ranking boosts.
    /// </summary>
    public class FileSignatureRecord
    {
        #region Public-Members

        /// <summary>
        /// Vessel identifier.
        /// </summary>
        public string VesselId { get; set; } = "";

        /// <summary>
        /// Repository-relative path.
        /// </summary>
        public string Path { get; set; } = "";

        /// <summary>
        /// Default-branch commit SHA represented by this signature.
        /// </summary>
        public string CommitSha { get; set; } = "";

        /// <summary>
        /// SHA-256 hash of the full file content.
        /// </summary>
        public string ContentHash { get; set; } = "";

        /// <summary>
        /// Detected language or file kind.
        /// </summary>
        public string Language { get; set; } = "";

        /// <summary>
        /// Natural-language file description generated by the inference client.
        /// </summary>
        public string Signature { get; set; } = "";

        /// <summary>
        /// Embedding vector generated from <see cref="Signature"/>, or null when unavailable.
        /// </summary>
        public float[]? SignatureVector { get; set; } = null;

        /// <summary>
        /// Signature generation timestamp in UTC.
        /// </summary>
        public DateTime GeneratedAtUtc { get; set; } = DateTime.UtcNow;

        #endregion
    }
}
