<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Touchstone.Cli" Version="0.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Armada.Test.Shared\Armada.Test.Shared.csproj" />
  </ItemGroup>

</Project>
