<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Touchstone.Core" Version="0.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Armada.Core\Armada.Core.csproj" />
    <ProjectReference Include="..\..\src\Armada.Runtimes\Armada.Runtimes.csproj" />
    <ProjectReference Include="..\..\src\Armada.Server\Armada.Server.csproj" />
    <ProjectReference Include="..\..\src\Armada.Proxy\Armada.Proxy.csproj" />
  </ItemGroup>

</Project>
